import {today,emptyState,importLegacy,submitProject,reviewProject,saveReport,summary} from './engine.js';
const KEY='chuangjie-projects-v1',director='创业者发展中心总监';
let state,raw,role=director,filter='全部',query='',asOf='',fault='';
try{raw=localStorage.getItem(KEY);state=raw?JSON.parse(raw):importLegacy(JSON.parse(localStorage.getItem('chuangjie-founders-v1')||localStorage.getItem('chuangjie-hr-v1')||'null'));if(!Array.isArray(state.projects))throw Error();if(!raw){raw=JSON.stringify(state);localStorage.setItem(KEY,raw);}}catch{state=emptyState();fault='本地数据读取失败，已保留原数据，暂不可提交。';}
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=v=>'¥'+Number(v).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const btn=(label,action,id='',cls='')=>`<button class="${cls}" data-action="${action}" data-id="${esc(id)}">${label}</button>`;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function close(){$('#overlay').innerHTML='';}
function modal(title,body){$('#overlay').innerHTML=`<div class="backdrop"><section class="drawer wide" role="dialog" aria-label="${esc(title)}"><div class="drawer-top"><h2>${esc(title)}</h2>${btn('关闭','close')}</div><div class="drawer-body">${body}</div></section></div>`;}
function commit(fn){try{if(fault)throw Error(fault);if(localStorage.getItem(KEY)!==raw)throw Error('其他页面已更新项目，请刷新后重试');const next=structuredClone(state);fn(next);next.revision++;const saved=JSON.stringify(next);localStorage.setItem(KEY,saved);state=next;raw=saved;close();render();toast('已保存');}catch(e){toast(e.message);}}
function phaseView(p,s){return p.phases.map((x,i)=>`<div class="stage-track"><div><b>第${i+1}阶段 · ${s.rates[i]}%</b><span>截止 ${esc(x.due)}</span></div><progress max="100" value="${s.rates[i]}"></progress><p>${esc(x.goal)}</p><small>阶段预算 ${money(x.budget)}${s.delayed.includes(i)?' · 已延期':''}</small></div>`).join('');}
function render(){const rows=state.projects.filter(p=>(filter==='全部'||p.status===filter)&&(!query||[p.name,p.owner,p.shop,p.license].join(' ').includes(query)));$('#app').innerHTML=`<main class="project-shell"><header class="project-head"><div><h1>项目全流程管理</h1><p>建立项目 → 总经理审核 → 月度陪跑与阶段结果跟踪</p></div><div class="actions"><label>模拟处理角色 <select aria-label="模拟处理角色" id="role">${[director,'总经理'].map(r=>`<option ${r===role?'selected':''}>${r}</option>`).join('')}</select></label>${role===director?btn('建立项目','new','','primary'):''}</div></header>${fault?`<p>${fault}</p>`:''}<div class="project-stats">${['全部','待总经理审核','管理中','已驳回'].map(s=>`<button class="project-stat ${filter===s?'active':''}" data-filter="${s}"><span>${s}</span><strong>${state.projects.filter(p=>s==='全部'||p.status===s).length}</strong></button>`).join('')}</div><div class="project-filters"><label>搜索项目 <input id="search" value="${esc(query)}" placeholder="项目、负责人、店铺或营业执照"></label><label>经营数据截至月份 <input id="asof" type="month" max="${today().slice(0,7)}" value="${esc(asOf)}"></label>${btn('查询','search')}${btn('重置','reset')}<span>金额按月累计，达成率取截至月份的最新记录</span></div><div class="project-cards">${rows.map(p=>{const s=summary(p,today(),asOf);return `<article class="project-card"><header><h2>${esc(p.name)}</h2><span class="badge">${p.status}</span></header><p class="context">负责人：${esc(p.owner)}<br>店铺：${esc(p.shop||'未填写')} · 营业执照：${esc(p.license||'未填写')}</p><div class="budget-line"><span>总预算 <b>${money(s.budget)}</b></span><span>累计使用 <b>${money(s.used)}</b></span><span>预算余额 <b>${money(s.remaining)}</b></span></div>${phaseView(p,s)}${s.overBudget?'<p class="risk-note">累计使用已超预算</p>':''}${s.missingMonth?'<p class="risk-note">该月份尚未更新陪跑记录</p>':''}<div class="latest-note">${s.latest?`<b>${esc(s.latest.month)} 项目评估</b><p>${esc(s.latest.assessment)}</p>`:'暂无月度陪跑记录'}</div><div class="actions">${btn('查看项目','detail',p.id)}${p.status==='管理中'&&role===director?btn('更新月度记录','report',p.id,'primary'):''}${p.status==='待总经理审核'&&role==='总经理'?btn('审核项目','review',p.id,'primary'):''}${p.status==='已驳回'&&role===director?btn('修改并重提','edit',p.id):''}</div></article>`;}).join('')||'<div class="project-empty">暂无符合条件的项目，可建立新项目或调整查询条件。</div>'}</div></main>`;}
function projectForm(p){modal(p?'修改项目并重提':'建立项目',`<form id="project-form" data-id="${p?.id||''}" class="phase-form"><label>项目名称<input name="name" required value="${esc(p?.name)}"></label><label>项目负责人<input name="owner" required value="${esc(p?.owner)}"></label><label>项目对应店铺<input name="shop" value="${esc(p?.shop)}"></label><label>项目对应营业执照<input name="license" value="${esc(p?.license)}"></label><p class="full">店铺与营业执照至少填写一项；两项都有请同时填写。</p>${[0,1,2].map(i=>`<fieldset class="full"><legend>第${i+1}阶段</legend><label>阶段目标<textarea name="goal${i}" required>${esc(p?.phases[i].goal)}</textarea></label><label>阶段预算（元）<input type="number" min="0.01" step="0.01" name="budget${i}" required value="${p?.phases[i].budget||''}"></label><label>截止时间<input type="date" min="${today()}" name="due${i}" required value="${p?.phases[i].due||''}"></label></fieldset>`).join('')}<button class="primary full" type="submit">提交总经理审核</button></form>`);}
function reportForm(p,month=today().slice(0,7)){const r=p.reports.find(x=>x.month===month),rates=r?.rates||summary(p,today(),month).rates;modal('更新月度陪跑记录',`<form id="report-form" data-id="${p.id}" class="phase-form"><label>月份<input id="report-month" name="month" type="month" required min="${p.approvedAt?.slice(0,7)||''}" max="${today().slice(0,7)}" value="${month}"></label><label>本月预算使用金额（元）<input name="used" type="number" min="0" step="0.01" required value="${r?.used??''}"></label><p class="full">填写当月新增使用金额，不是累计金额。同月再次保存会修订该月记录，保留历史版本。</p>${p.phases.map((x,i)=>`<label class="full">第${i+1}阶段目标达成率（%） · ${esc(x.goal)}<input name="rate${i}" type="number" min="0" max="100" step="0.01" required value="${rates[i]}"></label>`).join('')}<label class="full">项目评估<textarea name="assessment" required placeholder="本月进展、陪跑动作、问题卡点、运行结果与下月安排">${esc(r?.assessment)}</textarea></label><button type="submit" class="primary full">保存月度记录</button></form>`);}
function detail(p){const s=summary(p);modal(p.name,`<p>负责人：${esc(p.owner)} · ${p.status}</p><p>店铺：${esc(p.shop||'未填写')}<br>营业执照：${esc(p.license||'未填写')}</p><p>总预算 ${money(s.budget)} · 累计使用 ${money(s.used)} · 余额 ${money(s.remaining)}</p>${phaseView(p,s)}<h3>月度陪跑与运行结果</h3>${p.reports.slice().reverse().map(r=>`<article class="report-item"><b>${esc(r.month)} · 本月使用 ${money(r.used)}</b><p>阶段达成率：${r.rates.map((v,i)=>`第${i+1}阶段 ${v}%`).join(' / ')}</p><p>${esc(r.assessment)}</p><small>${esc(r.by)} · ${esc(r.updatedAt)}</small></article>`).join('')||'<p>暂无月度记录</p>'}<details><summary>月度修订历史（${p.reportHistory.length}）</summary>${p.reportHistory.map(r=>`<p>${esc(r.month)} · ${money(r.used)} · ${r.rates.join(' / ')}%<br>${esc(r.assessment)}</p>`).join('')}</details><h3>流程记录</h3><div class="project-timeline">${p.history.slice().reverse().map(h=>`<p><b>${esc(h.action)}</b> · ${esc(h.role)}<br>${esc(h.note)}<br><small>${esc(h.at)}</small></p>`).join('')}</div>`);}
document.addEventListener('click',e=>{const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;render();return;}const b=e.target.closest('[data-action]');if(!b)return;const p=state.projects.find(p=>p.id===b.dataset.id);switch(b.dataset.action){case'close':close();break;case'new':projectForm();break;case'edit':projectForm(p);break;case'detail':detail(p);break;case'report':reportForm(p);break;case'review':modal('总经理审核项目',`<p>${esc(p.name)} · 负责人 ${esc(p.owner)} · 总预算 ${money(summary(p).budget)}</p><p>店铺：${esc(p.shop||'未填写')} · 营业执照：${esc(p.license||'未填写')}</p>${phaseView(p,summary(p))}<form id="review-form" data-id="${p.id}"><label>审核结果<select name="result"><option>通过</option><option>驳回</option></select></label><label>审核意见<textarea name="note" required></textarea></label><button class="primary" type="submit">提交审核结果</button></form>`);break;case'search':query=$('#search').value.trim();asOf=$('#asof').value;render();break;case'reset':query='';asOf='';filter='全部';render();}});
document.addEventListener('change',e=>{if(e.target.id==='role'){role=e.target.value;close();render();}if(e.target.id==='report-month')reportForm(state.projects.find(p=>p.id===e.target.form.dataset.id),e.target.value);});
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f));if(f.id==='project-form')commit(s=>submitProject(s,{...d,id:f.dataset.id,phases:[0,1,2].map(i=>({goal:d['goal'+i],budget:d['budget'+i],due:d['due'+i]}))},role));if(f.id==='review-form')commit(s=>reviewProject(s,f.dataset.id,d.result,d.note,role));if(f.id==='report-form')commit(s=>saveReport(s,f.dataset.id,{...d,rates:[d.rate0,d.rate1,d.rate2]},role));});
window.addEventListener('storage',e=>{if(e.key===KEY){close();try{const next=JSON.parse(e.newValue);if(!Array.isArray(next.projects))throw Error();state=next;raw=e.newValue;render();toast('项目记录已同步其他页面的更新');}catch{fault='项目数据发生异常，请刷新检查';render();}}});
render();
