/* Global assistant stays outside #app so business renders cannot destroy its draft. */
let activeRecordId='',floatingAIOpen=false,aiMountedIdentity='';
const aiSessions=new Map();
const aiIdentity=()=>`${role}:${level}:${level==='员工'?employeeId:'manager'}`;
function aiSession(){const id=aiIdentity();if(!aiSessions.has(id))aiSessions.set(id,{messages:[],draft:''});return aiSessions.get(id);}
function aiContext(){const item=$('#overlay')?.children.length?state.items.find(i=>i.id===activeRecordId&&visible(i)):null;const label=menus().find(n=>n[0]===page)?.[2]||'当前页面';return {item,label:item?item.title:label};}
function syncAIContext(){const el=document.querySelector('#ai-context');if(el){const {label}=aiContext();el.textContent='当前上下文：'+label;}const who=document.querySelector('#ai-current-identity');if(who)who.textContent=centers[role]+' · '+(level==='员工'?(taskEmployees(role).find(e=>e.id===employeeId)?.name||'员工'):role===0?'老板':'负责人');}
function mountFloatingAI(){let root=document.querySelector('#floating-ai');if(!root){root=document.createElement('div');root.id='floating-ai';document.body.append(root);new MutationObserver(syncAIContext).observe($('#overlay'),{childList:true,subtree:true});}const identity=aiIdentity();if(aiMountedIdentity!==identity||!root.children.length){aiMountedIdentity=identity;const session=aiSession();root.innerHTML=`<button id="ai-launcher" aria-label="打开 AI 工作伙伴" aria-expanded="${floatingAIOpen}" aria-controls="ai-floating-panel" title="AI 工作伙伴"><span>✧</span><small>AI</small></button><section id="ai-floating-panel" class="ai-floating-panel" aria-label="AI 工作伙伴" ${floatingAIOpen?'':'hidden'}><div class="ai-floating-header"><div><b>✧ 创界 AI 工作伙伴</b><div id="ai-current-identity" class="sub"></div></div><button id="ai-minimize" aria-label="收起 AI 对话">—</button></div><div class="ai-floating-meta"><div id="ai-context"></div><span>本地规则演示 · 尚未连接模型</span></div><div id="chat" class="floating-chat" role="log" aria-live="polite"></div><div class="ai-quick-questions">${['帮我看当前事项','今天有哪些事项需要关注？','帮我拆解新品上新目标','平台基础视觉服务包含什么？','查询公司现金流和员工工资'].map(q=>`<button data-question="${q}">${q}</button>`).join('')}</div><form id="chat-form" class="floating-chat-form"><label class="sr-only" for="question">输入 AI 问题</label><textarea id="question" rows="2" placeholder="结合当前页面提问…" required>${esc(session.draft)}</textarea><button class="primary" type="submit">发送 ↑</button></form><div class="ai-floating-footer"><span>仅使用当前身份可见资料</span><button id="ai-clear-chat" class="flat">清空本身份对话</button></div></section>`;
root.querySelector('#ai-launcher').onclick=()=>floatingAIOpen?closeFloatingAI():openFloatingAI();root.querySelector('#ai-minimize').onclick=closeFloatingAI;root.querySelector('#chat-form').onsubmit=e=>{e.preventDefault();floatingAsk(root.querySelector('#question').value);};root.querySelector('#question').oninput=e=>aiSession().draft=e.target.value;root.querySelector('#question').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();floatingAsk(e.target.value);}};root.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>floatingAsk(b.dataset.question));root.querySelector('#ai-clear-chat').onclick=()=>{aiSession().messages=[];aiSession().draft='';root.querySelector('#question').value='';paintAIChat();};paintAIChat();}syncAIContext();}
function openFloatingAI(){floatingAIOpen=true;mountFloatingAI();$('#ai-floating-panel').hidden=false;$('#ai-launcher').setAttribute('aria-expanded','true');$('#question').focus();}
function closeFloatingAI(){floatingAIOpen=false;if($('#ai-floating-panel'))$('#ai-floating-panel').hidden=true;if($('#ai-launcher')){$('#ai-launcher').setAttribute('aria-expanded','false');$('#ai-launcher').focus();}}
function paintAIChat(){const el=$('#chat');if(!el)return;const messages=aiSession().messages;el.innerHTML=messages.length?messages.map(m=>`<div class="bubble ${m.who}">${esc(m.text)}${m.refs?.length?`<div class="ai-sources">${m.refs.filter(id=>state.items.some(i=>i.id===id&&visible(i))).map(id=>`<button data-ai-source="${id}">查看 ${id} ↗</button>`).join('')}</div>`:''}</div>`).join(''):'<div class="bubble">我可以结合当前任务或目标梳理要求、查看待办，或检索知识。<br>对话随时可收起，切换栏目后继续。AI 不代替负责人审批。</div>';el.querySelectorAll('[data-ai-source]').forEach(b=>b.onclick=()=>{if($('#overlay form')){toast('请先保存或关闭当前表单，再打开资料，避免丢失输入。');return;}detail(b.dataset.aiSource);syncAIContext();});el.scrollTop=el.scrollHeight;}
function floatingAsk(question){const q=question.trim();if(!q)return;openFloatingAI();const session=aiSession();session.messages.push({who:'user',text:q});let answer,refs=[];const {item}=aiContext();
if(role===1&&ceoShops.some(s=>!shops.includes(s.name)&&q.includes(s.name))){answer='该店铺不属于你负责的项目，无法查看其经营数据或事项。';}
else if(/当前|这个事项|这个任务/.test(q)&&item){if(item.type==='task'){answer=`任务：${item.title}\n执行人：${item.owner}\n任务说明和交付要求：${item.expected}\n验收标准：${item.standard||'待补充'}\n当前：${taskStatus[item.stage]}，进度 ${item.progress}%，截止 ${item.due}。${item.blocked?'\n阻碍：'+item.blocked:''}\n下一步：${item.stage===0?'由指定员工确认接收':item.stage===2?'等待负责人验收':item.stage===4?'已完成并归档':'员工完成工作后提交成果，负责人验收'}。`;refs=[item.id];}else if(item.type==='goal'){answer=`目标：${item.title}\n要的结果：${item.expected}\n当前：${goalStates[item.stage]}\n里程碑：${item.milestones.filter(goalComplete).length}/${item.milestones.length} 已交付。\n下一步：${item.stage===0?'负责人制定方案并承诺':item.stage===1?'老板审核方案':item.stage===3?'老板验收':item.stage===5?'已完成':'负责人完成各里程碑并上传成果后申请统一验收'}。`;refs=[item.id];}else{answer=`${item.title}\n当前环节：${stages[item.type][item.stage]}\n说明：${item.description}\n截止：${item.due}`;refs=[item.id];}}
else if(businessCanView()&&page==='overview'&&/经营|销售|利润|店铺|当前/.test(q)&&!/现金|工资|薪酬/.test(q)){const r=ceoReport();answer=`当前经营筛选：${ceoFilters.start} 至 ${ceoFilters.end}，${ceoFilters.shop==='all'?(role===0?'全部店铺':'我负责的全部店铺'):ceoShops.find(s=>s.id===ceoFilters.shop).name}。\n销售净额 ${ceoMoney(r.total.net)}；销售净成本 ${ceoMoney(r.total.cost)}；预估利润 ${ceoMoney(r.total.profit)}；预估利润率 ${ceoPct(r.total.margin)}。\n${r.comparable?'对比期 '+r.prev.start+' 至 '+r.prev.end+'；销售变化 '+ceoPct(ceoDirection(r.total.net,r.previous.net))+'。':'对比期不完整，不计算涨跌。'}\n来源：当前身份概览筛选范围内的演示日账本，未连接真实 ERP。`; }
else if(/任务|待办|关注|今天/.test(q)&&!/现金|工资|薪酬|其他项目/.test(q)){const arr=items().filter(t=>t.stage<stages[t.type].length-1&&(canAct(t)||t.light!=='green'||t.blocked));answer=arr.length?arr.map(t=>`${t.id}：${t.title}；${stages[t.type][t.stage]}；截止 ${t.due}${t.blocked?'；存在阻碍':''}。`).join('\n'):'当前身份没有待处理或异常事项。';refs=arr.map(t=>t.id);}
else{answer=aiAnswer(q);if(/目标|里程碑|拆解/.test(q))refs=items().filter(i=>i.type==='goal').map(i=>i.id);}
if(!answer)answer='当前页面没有打开具体事项。你可以先打开目标或任务详情，再让我梳理交付要求。';session.messages.push({who:'',text:answer+(refs.length?'\n来源：当前权限内的实时业务记录。':''),refs});session.draft='';$('#question').value='';paintAIChat();syncAIContext();}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&floatingAIOpen){e.preventDefault();e.stopImmediatePropagation();closeFloatingAI();}},true);
