/* CEO statistics for nodes from completed, human-started workflows. */
let ceoNodeCenter='all',ceoNodePerson='all';
const nodeDemoPeople={1:['林悦 · 事业主理人','小周 · 店铺运营','小许 · 运营助理'],2:['供应链负责人','小李 · 采购专员','小陈 · 商品专员','小唐 · 产品设计师'],3:['创业者发展中心负责人','小吴 · 创业者服务','小郑 · 行政专员'],4:['财务负责人','小赵 · 会计','小孙 · 财务助理'],5:['AI 科技中心负责人','小林 · 开发工程师','小何 · 技术支持'],6:['仓库负责人','小王 · 仓储专员','小刘 · 仓储专员'],7:['视觉负责人','小许 · 设计师','小周 · 视频制作']};
const nodeDemoCounts={1:[8,12,7],2:[9,13,10,8],3:[7,11,6],4:[10,14,7],5:[6,9,5],6:[8,15,6],7:[7,12,9]};
function migrateFlowNodes(){if(state.flowNodes||storageBlocked)return;try{const d=structuredClone(state),nodes=[];for(let center=1;center<=7;center++)nodeDemoPeople[center].forEach((person,p)=>{const total=nodeDemoCounts[center][p];for(let n=0;n<total;n++)nodes.push({id:`DEMO-${center}-${p}-${n}`,flowId:`HIST-${center}-${Math.floor(n/3)+1}`,center,person,node:n%4===0?'发起':n%3===0?'审批 / 验收':'执行节点',date:`2026-09-${String(2+(n*3+p)%22).padStart(2,'0')}`,source:'historical-demo',completed:true});});d.flowNodes={version:1,nodes};d.revision=(state.revision||0)+1;localStorage.setItem(key,JSON.stringify(d));state=d;}catch{storageBlocked=true;}}
function nodeIsAutomatic(i){return i.source==='system'||!!i.cycleKey||i.history?.[0]?.includes('首次入库事件')||i.history?.[0]?.includes('系统按周期自动生成')||i.history?.[0]?.includes('系统生成固定盘点清单');}
function nodeSuccessfulStages(i){return (stages[i.type]||[]).filter(n=>!/(已完成|退回|驳回|补充)/.test(n));}
function nodeCenter(i,stage){if(i.type==='stock')return stage===3?4:6;if(i.type==='service')return stage===0?3:stage===2?1:(i.assigned||3);if(i.type==='purchase')return stage===2?6:2;if(i.type==='visual')return 7;if(typeof isLifeTask==='function'&&isLifeTask(i))return stage<2?1:2;return i.center||1;}
function nodePerson(i,stage){const center=nodeCenter(i,stage);if(i.type==='task')return stage===0?(i.manager||centers[i.center]+'负责人'):(i.owner||nodeDemoPeople[center]?.[0]);if(i.type==='stock')return stage<2?stockPerson(i.assigneeId):stage===2?'仓库负责人':'小赵 · 会计';if(i.type==='develop')return stage===1?developmentPerson(i.designerId):stage===3?developmentPerson(i.followerId):'供应链负责人';if(['purchase','service'].includes(i.type)&&i.assigneeId&&stage>0)return taskEmployees(center).find(e=>e.id===i.assigneeId)?.name||centers[center]+'负责人';if(typeof isLifeTask==='function'&&isLifeTask(i))return stage<2?(ceoShops.find(s=>s.name===i.shop)?.owner||i.owner):'供应链负责人';return i.owner||nodeDemoPeople[center]?.[0]||centers[center]+'负责人';}
function completedItemNodes(i){if(!ceoIsDone(i)||nodeIsAutomatic(i))return [];const date=i.completedAt||i.approvedOn||i.due||'2026-09-24',flowId=i.id,out=[],creatorCenter=i.type==='goal'?0:(['service','purchase'].includes(i.type)?1:i.center||1);if(creatorCenter>0)out.push({id:flowId+'-start',flowId,center:creatorCenter,person:['service','purchase'].includes(i.type)?'林悦 · 事业主理人':i.creatorId&&typeof developmentPerson==='function'?developmentPerson(i.creatorId):i.owner||centers[creatorCenter]+'负责人',node:'发起',date,source:'live',completed:true,title:i.title});nodeSuccessfulStages(i).forEach((node,stage)=>out.push({id:flowId+'-'+stage,flowId,center:nodeCenter(i,stage),person:nodePerson(i,stage),node:/审核|审批|验收|评价|复核|受理/.test(node)?'审批 / 验收':node,date,source:'live',completed:true,title:i.title}));return out;}
function ceoNodeRows(){const stored=state.flowNodes?.nodes||[],ids=new Set(stored.map(n=>n.flowId));return [...stored,...state.items.filter(i=>!ids.has(i.id)).flatMap(completedItemNodes)].filter(n=>n.completed&&n.source!=='system');}
function ceoNodeDashboard(){const all=ceoNodeRows().filter(n=>ceoManagement.month==='all'||n.date.startsWith(ceoManagement.month)),scoped=all.filter(n=>(ceoNodeCenter==='all'||n.center===Number(ceoNodeCenter))&&(ceoNodePerson==='all'||n.person===ceoNodePerson)),people=[...new Set(all.filter(n=>ceoNodeCenter==='all'||n.center===Number(ceoNodeCenter)).map(n=>n.person))].sort();const group=arr=>Object.values(arr.reduce((m,n)=>{const v=n.person;(m[v]??={name:v,nodes:0,flows:new Set(),launch:0,approval:0,center:n.center});m[v].nodes++;m[v].flows.add(n.flowId);if(n.node==='发起')m[v].launch++;if(n.node==='审批 / 验收')m[v].approval++;return m;},{}));const departments=centers.slice(1).map((name,k)=>{const arr=scoped.filter(n=>n.center===k+1);return {name,center:k+1,nodes:arr.length,flows:new Set(arr.map(n=>n.flowId)).size,people:new Set(arr.map(n=>n.person)).size};}),employees=group(scoped).sort((a,b)=>b.nodes-a.nodes||a.name.localeCompare(b.name));return `<section class="ceo-node-dashboard"><div class="ceo-section-title compact"><div><h3>已完结流程节点</h3><span class="sub">只统计人工发起且已完结的流程；发起、执行、审批和验收均算节点</span></div><span class="badge">${scoped.length} 个节点 · ${new Set(scoped.map(n=>n.flowId)).size} 条流程</span></div><div class="ceo-node-controls"><label>部门<select id="ceo-node-center"><option value="all">全部中心</option>${centers.slice(1).map((c,n)=>`<option value="${n+1}" ${ceoNodeCenter===String(n+1)?'selected':''}>${c}</option>`).join('')}</select></label><label>员工<select id="ceo-node-person"><option value="all">全部员工</option>${people.map(p=>`<option value="${esc(p)}" ${ceoNodePerson===p?'selected':''}>${esc(p)}</option>`).join('')}</select></label><button id="ceo-node-reset">重置节点筛选</button></div><div class="ceo-node-departments">${departments.map(d=>`<button data-node-center="${d.center}" class="${ceoNodeCenter===String(d.center)?'selected':''}"><span>${d.name}</span><strong>${d.nodes}</strong><small>节点 · ${d.flows} 条完结流程 · ${d.people} 人</small></button>`).join('')}</div><section class="panel"><div class="panel-head"><h2>员工完成节点明细</h2><span class="sub">点击员工查看其已计入的节点</span></div><div class="table-wrap"><table><thead><tr><th>员工</th><th>所属中心</th><th>完成节点</th><th>参与完结流程</th><th>其中发起</th><th>其中审批 / 验收</th><th></th></tr></thead><tbody>${employees.map(e=>`<tr><td><b>${esc(e.name)}</b></td><td>${centers[e.center]}</td><td><strong>${e.nodes}</strong></td><td>${e.flows.size}</td><td>${e.launch}</td><td>${e.approval}</td><td><button data-node-person="${esc(e.name)}">查看节点</button></td></tr>`).join('')}</tbody></table></div>${employees.length?'':'<div class="empty">当前筛选范围暂无已完结的人工流程节点。</div>'}</section><p class="ceo-period">演示中的历史节点标记为“历史演示”；后续真实流程只有达到最终完成状态才会整体计入。退回动作不重复计数，系统周期任务、ERP 自动生成工单不参与统计。</p></section>`;}
function ceoNodeDetail(person){const rows=ceoNodeRows().filter(n=>(ceoManagement.month==='all'||n.date.startsWith(ceoManagement.month))&&n.person===person);modal(person+' · 完成节点',`<div class="notice">共 ${rows.length} 个节点，来自 ${new Set(rows.map(n=>n.flowId)).size} 条已完结人工流程。</div><div class="timeline">${rows.sort((a,b)=>b.date.localeCompare(a.date)).map(n=>`<div><b>${esc(n.node)}</b> · ${esc(n.title||n.flowId)}<small>${n.date} · ${centers[n.center]} · ${n.source==='historical-demo'?'历史演示':'当前业务记录'}</small></div>`).join('')}</div>`);$('.modal').classList.add('goal-modal');}
function bindCeoNodes(){if($('#ceo-node-center'))$('#ceo-node-center').onchange=e=>{ceoNodeCenter=e.target.value;ceoNodePerson='all';render();};if($('#ceo-node-person'))$('#ceo-node-person').onchange=e=>{ceoNodePerson=e.target.value;render();};if($('#ceo-node-reset'))$('#ceo-node-reset').onclick=()=>{ceoNodeCenter='all';ceoNodePerson='all';render();};document.querySelectorAll('[data-node-center]').forEach(b=>b.onclick=()=>{ceoNodeCenter=b.dataset.nodeCenter;ceoNodePerson='all';render();});document.querySelectorAll('[data-node-person]').forEach(b=>b.onclick=()=>ceoNodeDetail(b.dataset.nodePerson));}
