let pw;try{pw=require('@playwright/test');}catch{pw=require('/Users/guole/Documents/ChatGPT/总经理工作台/node_modules/@playwright/test');}
const assert=require('node:assert/strict');const fs=require('node:fs/promises');
(async()=>{
const browser=await pw.chromium.launch({headless:true,channel:'chrome'});const context=await browser.newContext({viewport:{width:1440,height:1050}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:4173');
const store=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('chuangjie-platform-demo-v1')));
const goal=async id=>(await store()).items.find(i=>i.id===id);
const nav=async p=>page.locator('nav [data-page="'+p+'"]').click();
const close=async()=>{if(await page.locator('#close').count())await page.click('#close');};
const role=async(r,level='负责人')=>{if(await page.locator('#ai-launcher').getAttribute('aria-expanded')==='true')await page.click('#ai-minimize');await close();await page.selectOption('#role',String(r));if(r>1)await page.selectOption('#level',level);await nav('goals');};
const open=async id=>{await close();await nav('goals');await page.locator('[data-goal-row="'+id+'"] [data-open]').first().click();};
async function createGoal(r,title){await role(0);await page.locator('[data-new="goal"]').click();await page.selectOption('#goal-center',String(r));if(r===1)await page.selectOption('#goal-shop','银器生活店');await page.fill('#goal-title',title);await page.fill('#goal-why','验证跨中心数据连通，减少协作等待');await page.fill('#goal-expected','两项里程碑有可查验成果并完成最终验收');await page.fill('#goal-plan-due','2026-09-28');await page.fill('#goal-due','2026-10-15');await page.locator('#goal-create-form button[type="submit"]').click();const g=(await store()).items.find(i=>i.title===title);assert.ok(g);return g.id;}
const id=await createGoal(2,'测试：新品交付目标闭环');assert.equal((await goal(id)).stage,0);assert.equal((await goal(id)).why,'验证跨中心数据连通，减少协作等待');
await page.click('#goal-edit');await page.fill('#goal-expected','两项里程碑分别有成果，全部交付后由老板统一验收');await page.locator('#goal-create-form button[type="submit"]').click();assert.match((await goal(id)).expected,/老板统一验收/);
await role(2,'员工');await open(id);assert.equal(await page.locator('#goal-plan').count(),0);await role(2);await open(id);await page.click('#goal-plan');await page.fill('#goal-standard','每个里程碑均有完整报告，最终验收无遗漏。');await page.fill('[name="milestone-title"]','完成选品评估');await page.fill('[name="milestone-start"]','2026-09-28');await page.fill('[name="milestone-end"]','2026-10-01');await page.click('#goal-add-milestone');await page.locator('[name="milestone-title"]').nth(1).fill('完成样品确认');await page.locator('[name="milestone-start"]').nth(1).fill('2026-10-02');await page.locator('[name="milestone-end"]').nth(1).fill('2026-10-10');await page.click('#goal-add-milestone');await page.locator('[data-remove-milestone="2"]').click();assert.equal(await page.locator('.milestone-edit').count(),2);await page.fill('#goal-commitment','承诺按期交付选品和样品确认报告。');await page.click('#goal-save-draft');assert.equal((await goal(id)).milestones.length,2);assert.equal((await goal(id)).stage,0);
await page.reload();await role(2);await open(id);await page.click('#goal-plan');assert.equal(await page.locator('[name="milestone-title"]').nth(1).inputValue(),'完成样品确认');await page.locator('#goal-plan-form button[type="submit"]').click();assert.equal((await goal(id)).stage,0);await page.check('#goal-pledge');await page.locator('[name="milestone-start"]').first().fill('2026-10-05');await page.locator('#goal-plan-form button[type="submit"]').click();assert.equal((await goal(id)).stage,0);await page.locator('[name="milestone-start"]').first().fill('2026-09-28');await page.locator('#goal-plan-form button[type="submit"]').click();assert.equal((await goal(id)).stage,1);
await role(0);await nav('tasks');await page.locator('[data-filter="pending"]').click();assert.ok(await page.locator('[data-open="'+id+'"]').count());await page.locator('[data-open="'+id+'"]').click();await page.click('#goal-plan-reject');await page.fill('#goal-decision-note','请补充质量核对标准');await page.locator('#goal-decision-form .primary').click();assert.equal((await goal(id)).stage,0);
await role(2);await open(id);assert.match(await page.locator('.rejection').innerText(),/质量核对/);await page.click('#goal-plan');await page.fill('#goal-standard','报告齐备，样品质量全部达到约定标准。');await page.check('#goal-pledge');await page.locator('#goal-plan-form button[type="submit"]').click();await role(0);await open(id);await page.click('#goal-plan-approve');await page.locator('#goal-decision-form .primary').click();assert.equal((await goal(id)).stage,2);assert.ok((await goal(id)).startedAt);assert.equal((await store()).items.filter(i=>i.type==='task').length,0);
await role(2);await open(id);assert.equal(await page.locator('#goal-request-acceptance').isDisabled(),true);const mids=(await goal(id)).milestones.map(m=>m.id);
await page.locator('[data-milestone-deliver="'+mids[0]+'"]').click();await page.click('#goal-delivery-submit');assert.equal((await goal(id)).progress,0);const proof=Buffer.from('真实里程碑成果文件：选品评估通过。','utf8');await page.setInputFiles('#goal-evidence-files',{name:'选品报告.txt',mimeType:'text/plain',buffer:proof});await page.click('#goal-delivery-submit');await page.locator('[data-evidence-download]').waitFor();assert.equal((await goal(id)).progress,50);assert.equal(await page.locator('#goal-request-acceptance').isDisabled(),true);
await page.reload();await role(0);await open(id);const downloadP=page.waitForEvent('download');await page.locator('[data-evidence-download]').click();const dl=await downloadP;assert.deepEqual(await fs.readFile(await dl.path()),proof);assert.equal(await page.locator('[data-milestone-deliver]').count(),0);
await role(2);await open(id);await page.locator('[data-milestone-deliver="'+mids[1]+'"]').click();await page.fill('#goal-evidence-text','样品尺寸、克重与工艺检验均通过。');await page.fill('#goal-evidence-url','https://example.com/sample-report');await page.click('#goal-delivery-submit');assert.equal((await goal(id)).progress,100);assert.equal(await page.locator('#goal-request-acceptance').isDisabled(),false);
// Reopen preserves evidence and blocks acceptance until resubmitted.
await page.locator('[data-milestone-reopen="'+mids[1]+'"]').click();await page.fill('#goal-reopen-reason','补充测试结论');await page.locator('#goal-reopen-form .primary').click();assert.equal((await goal(id)).progress,50);await page.locator('[data-milestone-deliver="'+mids[1]+'"]').click();await page.fill('#goal-evidence-text','补充测试通过，样品符合质量标准。');await page.click('#goal-delivery-submit');await page.locator('[data-milestone-history="'+mids[1]+'"]').click();assert.match(await page.locator('.modal').innerText(),/尺寸、克重/);await page.click('#goal-history-back');await page.click('#goal-request-acceptance');assert.equal((await goal(id)).stage,3);assert.equal(await page.locator('[data-milestone-deliver]').count(),0);
await role(0);await open(id);await page.click('#goal-final-reject');await page.fill('#goal-decision-note','样品报告需要补充耐用性验证');await page.locator('[name="rework-milestone"]').first().uncheck();await page.locator('#goal-decision-form .primary').click();assert.equal((await goal(id)).stage,4);assert.equal((await goal(id)).progress,50);assert.equal((await goal(id)).milestones[0].status,'complete');
await role(2);await open(id);assert.match(await page.locator('.rejection').innerText(),/耐用性/);await page.locator('[data-milestone-deliver="'+mids[1]+'"]').click();await page.fill('#goal-evidence-text','已完成耐用性验证，结果合格。');await page.click('#goal-delivery-submit');await page.click('#goal-request-acceptance');await role(0);await open(id);await page.screenshot({path:'artifacts/06-goal-acceptance.png',fullPage:true});await page.click('#goal-final-approve');await page.fill('#goal-decision-note','资料完整，达到预期结果，验收通过。');await page.locator('#goal-decision-form .primary').click();assert.equal((await goal(id)).stage,5);assert.equal(await page.locator('#goal-final-approve').count(),0);assert.equal((await store()).docs.filter(d=>d.id==='GOAL-RESULT-'+id).length,1);
await page.click('#goal-versions');assert.match(await page.locator('.modal').innerText(),/方案 v2/);assert.match(await page.locator('.modal').innerText(),/最终验收驳回/);await page.click('#goal-version-back');await page.click('#goal-records');assert.ok(await page.locator('[data-doc="GOAL-RESULT-'+id+'"]').count());await page.locator('[data-doc="GOAL-RESULT-'+id+'"]').click();await page.click('#doc-goal-link');assert.match(await page.locator('.modal').innerText(),/已完成/);const exportP=page.waitForEvent('download');await page.click('#goal-export');const exported=JSON.parse(await fs.readFile(await(await exportP).path(),'utf8'));assert.equal(exported.id,id);assert.equal(exported.stage,5);await page.click('#goal-back-list');await page.fill('#goal-search','新品交付目标闭环');await page.click('#goal-search-submit');assert.equal(await page.locator('[data-goal-row]').count(),1);await page.locator('[data-goal-filter="done"]').click();assert.equal(await page.locator('[data-goal-row]').count(),1);await page.click('#goal-clear-search');
console.log('PASS: boss create/edit; owner draft/commitment/dates; plan reject/review; start; real upload/download; per-milestone progress; reopen; final reject/rework/pass; versions/knowledge links/export/search');
// Each center receives a target from the same store. Principal receives the selected shop.
for(let r=1;r<=7;r++){const id2=await createGoal(r,'路由测试中心 '+r);await role(r);assert.ok(await page.locator('[data-goal-row="'+id2+'"]').count());await open(id2);assert.ok(await page.locator('#goal-plan').count());if(r===1)assert.equal((await goal(id2)).shop,'银器生活店');await role(r===7?2:7);assert.equal(await page.locator('[data-goal-row="'+id2+'"]').count(),0);}
await role(0);await page.screenshot({path:'artifacts/07-goals-list.png',fullPage:true});
// Home links reference accessible current targets, not a hard-coded supply goal.
await role(1);await nav('overview');await page.locator('.guide button').click();assert.match(await page.locator('.modal').innerText(),/林悦/);await close();await role(2);await nav('ai');await page.locator('[data-question="帮我拆解新品上新目标"]').click();assert.match(await page.locator('#chat').innerText(),/新品交付目标闭环/);
// Same-origin cross-tab changes synchronize when not editing.
const other=await context.newPage();await other.goto('http://localhost:4173');const next=await createGoal(3,'跨标签同步目标');await other.locator('nav [data-page="goals"]').click();assert.ok(await other.locator('[data-goal-row="'+next+'"]').count());await other.close();
await role(2);await open(id);await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'artifacts/08-goal-mobile.png',fullPage:true});assert.deepEqual(errors,[]);
// Migration keeps the original state and never invents milestone evidence.
const legacyContext=await browser.newContext();const legacyPage=await legacyContext.newPage();await legacyPage.addInitScript(()=>localStorage.setItem('chuangjie-platform-demo-v1',JSON.stringify({version:1,seq:901,items:[{id:'CJ-900',type:'goal',title:'历史完成目标',center:1,shop:'公司',stage:9,due:'2026-09-30',light:'green',progress:100,description:'历史描述',history:['历史验收完成']}],docs:[],log:[]})));await legacyPage.goto('http://localhost:4173');const migration=await legacyPage.evaluate(()=>({data:JSON.parse(localStorage.getItem('chuangjie-platform-demo-v1')),backup:JSON.parse(localStorage.getItem('chuangjie-platform-demo-v1-before-goals-v2'))}));assert.equal(migration.backup.items[0].stage,9);assert.equal(migration.data.items[0].legacyGoal.stage,9);assert.equal(migration.data.items[0].stage,0);assert.equal(migration.data.items[0].milestones.length,0);assert.equal(migration.data.items[0].shop,'归银堂旗舰店');
console.log('PASS: all 7 recipient routes, principal shop mapping, employee read-only, accessible home links, live AI target data, cross-tab sync, mobile layout, lossless migration, no browser errors');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
