let pw;try{pw=require('@playwright/test');}catch{pw=require('/Users/guole/Documents/ChatGPT/总经理工作台/node_modules/@playwright/test');}const assert=require('node:assert/strict');
(async()=>{const browser=await pw.chromium.launch({headless:true,channel:'chrome'});const p=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:4173');
for(let r=1;r<=7;r++){
await p.selectOption('#role',String(r));await p.locator('nav [data-page="dispatch"]').click();await p.locator('[data-new="task"]').click();
assert.match(await p.locator('label:has(#task-description)').innerText(),/^为什么做$/);assert.match(await p.locator('label:has(#task-expected)').innerText(),/^任务说明和交付要求$/);
const order=await p.locator('#task-create-form input').evaluateAll(es=>es.map(e=>e.id));assert.deepEqual(order.slice(0,3),['task-title','task-start','task-due']);
await p.fill('#task-start','2026-12-31');await p.click('[data-task-days="3"]');assert.equal(await p.inputValue('#task-due'),'2027-01-02');await p.click('[data-task-days="1"]');assert.equal(await p.inputValue('#task-due'),'2026-12-31');await p.fill('#task-start','2028-02-28');await p.click('[data-task-days="3"]');assert.equal(await p.inputValue('#task-due'),'2028-03-01');await p.fill('#task-days','4');assert.equal(await p.inputValue('#task-due'),'2028-03-02');await p.fill('#task-due','2028-03-05');assert.equal(await p.inputValue('#task-days'),'7');await p.fill('#task-start','2026-09-24');await p.locator('#task-title').click();assert.equal(await p.inputValue('#task-due'),'2026-09-30');
const priority=['紧急','重要','普通'][(r-1)%3];await p.fill('#task-title','格式验证中心'+r);await p.fill('#task-description','提高效率');await p.fill('#task-expected','完成工作并交付报告');await p.fill('#task-standard','内容齐全');await p.selectOption('#task-priority',priority);if(r===1)await p.screenshot({path:'artifacts/task-format-form.png',fullPage:true});await p.locator('#task-create-form .primary').click();assert.equal(await p.locator('.modal [data-priority]').getAttribute('data-priority'),priority);await p.click('#task-back');const row=p.locator('[data-task-row]').filter({hasText:'格式验证中心'+r});assert.equal(await row.locator('[data-priority]').getAttribute('data-priority'),priority);
await p.selectOption('#level','员工');await p.locator('nav [data-page="dispatch"]').click();assert.equal(await p.locator('[data-task-row]').filter({hasText:'格式验证中心'+r}).locator('[data-priority]').getAttribute('data-priority'),priority);await p.selectOption('#level','负责人');
}
await p.reload();await p.selectOption('#role','7');await p.locator('nav [data-page="dispatch"]').click();assert.equal(await p.locator('[data-task-row]').filter({hasText:'格式验证中心7'}).locator('[data-priority]').getAttribute('data-priority'),'紧急');await p.screenshot({path:'artifacts/task-priority-list.png',fullPage:true});assert.deepEqual(errors,[]);await browser.close();console.log('PASS: 7 centers form labels/order, natural-day shortcuts, year/leap-month boundary, custom/manual dates, manager/employee priority, persistence, no page errors');})().catch(e=>{console.error(e);process.exit(1)});
