let pw;try{pw=require('@playwright/test');}catch{pw=require('/Users/guole/Documents/ChatGPT/总经理工作台/node_modules/@playwright/test');}const assert=require('node:assert/strict');const fs=require('node:fs/promises');
(async()=>{const browser=await pw.chromium.launch({headless:true,channel:'chrome'});const ctx=await browser.newContext({viewport:{width:1440,height:1050}});const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:4173');const data=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('chuangjie-platform-demo-v1')));const task=async id=>(await data()).items.find(x=>x.id===id);const nav=async x=>p.locator('nav [data-page="'+x+'"]').click();
async function closeAI(){if(await p.locator('#ai-launcher').getAttribute('aria-expanded')==='true')await p.click('#ai-minimize');}async function close(){await closeAI();if(await p.locator('#close').count())await p.click('#close');}
async function role(r,l='负责人',employee=1){await close();await p.selectOption('#role',String(r));if(r>0)await p.selectOption('#level',l);if(l==='员工')await p.selectOption('#employee',`emp-${r}-${employee}`);await nav(r?'dispatch':'tasks');}
async function open(id){await close();await p.locator('[data-open="'+id+'"]').first().click();}
async function create(r,title,emp=1){await role(r);await p.locator('[data-new="task"]').click();await p.fill('#task-title',title);await p.selectOption('#task-assignee',`emp-${r}-${emp}`);await p.fill('#task-description','准备新品资料，解决信息不一致');await p.fill('#task-expected','提交完整可核对的资料表');await p.fill('#task-standard','编码、尺寸与重量字段全部齐全');await p.fill('#task-start','2026-09-24');await p.fill('#task-due','2026-10-02');await p.locator('#task-create-form .primary').click();const t=(await data()).items.find(t=>t.title===title);assert.ok(t);return t.id;}
// Global AI appears on every page and sends without destroying forms.
await p.click('#ai-launcher');await p.fill('#question','尚未发送的问题');await nav('goals');assert.equal(await p.locator('#question').inputValue(),'尚未发送的问题');await p.locator('[data-question="今天有哪些事项需要关注？"]').click();const msgs=await p.locator('#chat').innerText();await p.click('#ai-minimize');await nav('knowledge');await p.click('#ai-launcher');assert.equal(await p.locator('#chat').innerText(),msgs);await closeAI();await nav('goals');await p.locator('[data-new="goal"]').click();await p.fill('#goal-title','不能被 AI 刷新的输入');await p.click('#ai-launcher');await p.fill('#question','平台基础视觉服务包含什么？');await p.locator('#chat-form button').click();assert.equal(await p.locator('#goal-title').inputValue(),'不能被 AI 刷新的输入');await p.keyboard.press('Escape');assert.equal(await p.locator('#ai-floating-panel').isVisible(),false);assert.equal(await p.locator('#goal-title').inputValue(),'不能被 AI 刷新的输入');await close();
const id=await create(5,'测试：完整部门任务',1);assert.equal((await task(id)).stage,0);assert.equal((await task(id)).owner,'小林 · 开发工程师');await p.click('#task-edit');await p.selectOption('#task-assignee','emp-5-2');await p.fill('#task-edit-reason','调整工作分工');await p.locator('#task-create-form .primary').click();assert.equal((await task(id)).assigneeId,'emp-5-2');
await role(5,'员工',1);assert.equal(await p.locator('[data-open="'+id+'"]').count(),0);await nav('knowledge');assert.equal(await p.locator('[data-doc="TASK-FLOW-'+id+'"]').count(),0);await role(5,'员工',2);await open(id);assert.equal(await p.locator('#task-deliver').count(),0);await p.click('#task-accept');assert.equal((await task(id)).stage,1);await p.click('#task-update');await p.fill('#task-progress','45');await p.fill('#task-update-note','已整理主要商品字段');await p.fill('#task-blocker','等待供应商重量信息');await p.locator('#task-update-form .primary').click();assert.equal((await task(id)).progress,45);await p.click('#ai-launcher');await p.locator('[data-question="帮我看当前事项"]').click();assert.match(await p.locator('#chat').innerText(),/等待供应商重量信息/);await p.screenshot({path:'artifacts/09-floating-ai-task.png',fullPage:true});await closeAI();
await p.click('#task-request-extension');await p.fill('#task-new-due','2026-10-05');await p.fill('#task-extension-reason','供应商资料需要补齐');await p.locator('#task-extension-form .primary').click();assert.equal((await task(id)).extension.status,'pending');await role(5);await nav('tasks');await p.locator('[data-filter="pending"]').click();assert.ok(await p.locator('[data-open="'+id+'"]').count());await open(id);await p.click('#task-review-extension');await p.fill('#task-extension-review-note','支持补齐资料，延长三天');await p.locator('#task-extension-review-form .primary').click();assert.equal((await task(id)).due,'2026-10-05');assert.equal((await task(id)).extension.status,'approved');
await role(5,'员工',2);await open(id);await p.click('#task-deliver');await p.click('#task-deliver-submit');assert.equal((await task(id)).stage,1);const proof=Buffer.from('可核对的任务成果文件');await p.setInputFiles('#task-files',{name:'资料表.txt',mimeType:'text/plain',buffer:proof});await p.fill('#task-result','所有字段已核对完整');await p.click('#task-deliver-submit');await p.locator('[data-task-download]').waitFor();assert.equal((await task(id)).stage,2);assert.equal((await task(id)).progress,99);assert.equal(await p.locator('#task-approve').count(),0);
await p.reload();await role(5);await open(id);const download=p.waitForEvent('download');await p.locator('[data-task-download]').click();assert.deepEqual(await fs.readFile(await(await download).path()),proof);await p.click('#task-reject');await p.fill('#task-review-note','请补充最后一款的克重来源');await p.locator('#task-review-form .primary').click();assert.equal((await task(id)).stage,3);await role(5,'员工',2);await open(id);assert.match(await p.locator('.rejection').innerText(),/克重来源/);await p.click('#task-deliver');await p.fill('#task-result','已补充供应商原始克重凭据');await p.locator('#task-deliver-form .primary').click();assert.equal((await task(id)).deliveries.length,1);await role(5);await open(id);await p.click('#task-approve');await p.locator('#task-review-form .primary').click();assert.equal((await task(id)).stage,4);assert.equal((await task(id)).progress,100);await p.click('#task-records');await p.locator('[data-doc="TASK-RESULT-'+id+'"]').click();await p.click('#doc-task-link');assert.match(await p.locator('.modal').innerText(),/已完成/);await p.click('#task-delivery-history');assert.ok(await p.locator('[data-task-download]').count());await p.click('#task-history-back');await p.click('#task-back');await p.fill('#task-search','完整部门任务');await p.click('#task-search-submit');await p.locator('[data-task-filter="4"]').click();assert.equal(await p.locator('[data-task-row]').count(),1);await p.click('#task-search-clear');await p.screenshot({path:'artifacts/10-task-management.png',fullPage:true});
console.log('PASS: floating AI, cross-page conversation/draft, form preservation, Escape; task assign/reassign, per-employee isolation, accept/update/blocker, extension, real upload/download, rejection/resubmission, manager completion, archive links/search');
// Every center can dispatch to an actual selected employee, including principal's store team.
for(let r=1;r<=7;r++){const tid=await create(r,'派单路由中心 '+r,2);await role(r,'员工',1);assert.equal(await p.locator('[data-open="'+tid+'"]').count(),0);await role(r,'员工',2);assert.ok(await p.locator('[data-open="'+tid+'"]').count());await open(tid);await p.click('#task-accept');assert.equal((await task(tid)).stage,1);}
// Identity-specific chats are not shown to another center or employee.
await role(5,'员工',2);await p.click('#ai-launcher');await p.fill('#question','测试身份独有对话');await p.locator('#chat-form button').click();assert.match(await p.locator('#chat').innerText(),/测试身份独有对话/);await role(5,'员工',1);await p.click('#ai-launcher');assert.doesNotMatch(await p.locator('#chat').innerText(),/测试身份独有对话/);await p.locator('[data-question="查询公司现金流和员工工资"]').click();assert.match(await p.locator('#chat').innerText(),/超出当前角色/);await role(5,'员工',2);await p.click('#ai-launcher');assert.match(await p.locator('#chat').innerText(),/测试身份独有对话/);
// Source links respect unsaved forms; closed panel remains reachable on small screens.
await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:'artifacts/11-floating-ai-mobile.png',fullPage:true});await closeAI();assert.equal(await p.locator('#ai-launcher').isVisible(),true);assert.deepEqual(errors,[]);await browser.close();console.log('PASS: 7 centers assignment routing, principal employees, separate persona histories, AI permission refusal, mobile layout, no browser errors');})().catch(e=>{console.error(e);process.exit(1)});
