import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import {webcrypto} from 'node:crypto';
import * as engine from '../hr/engine.js';
import * as ops from '../hr/operations.js';
import * as onboarding from '../hr/onboarding.js';
import * as policy from '../hr/workflow-policy.js';
const source=fs.readFileSync(new URL('../cross-approvals.js',import.meta.url),'utf8').replace(/^const crossBusiness=.*$/m,'const crossBusiness=Promise.resolve(BUSINESS);');
function fixture(){const db=new Map(),s=ops.migrate(engine.seed());s.processes=[];s.docRequests=[];s.requests=[];s.candidates=[];const c=vm.createContext({BUSINESS:{engine,ops,onboarding,policy},Date,Intl,crypto:webcrypto,JSON,console,role:3,level:'负责人',employeeId:'emp-3-2',centers:['老板','运营','供应链','发展中心','财务'],taskEmployees:()=>[{id:'emp-3-2',name:'行政专员'}],localStorage:{getItem:k=>db.get(k)||null,setItem:(k,v)=>db.set(k,v),removeItem:k=>db.delete(k)}});vm.runInContext(source,c);const put=(s,k='chuangjie-hr-v1')=>db.set(k,JSON.stringify(s));put(s);return {s,c,db,put,run:code=>vm.runInContext(code,c),read:(k='chuangjie-hr-v1')=>JSON.parse(db.get(k))};}
test('到期当天正常、满三个自然日红灯、批准延期黄灯且红灯不降级',()=>{assert.equal(policy.deadlineLight('2026-09-27',{now:'2026-09-27T20:00:00+08:00'}),'green');assert.equal(policy.deadlineLight('2026-09-27',{now:'2026-09-28T00:00:00+08:00'}),'yellow');assert.equal(policy.deadlineLight('2026-09-27',{now:'2026-10-01T00:00:00+08:00'}),'red');assert.equal(policy.deadlineLight('2026-10-05',{now:'2026-09-27T00:00:00+08:00',extended:true}),'yellow');assert.equal(policy.deadlineLight('2026-10-05',{previous:'red'}),'red');});
test('缺少整改期限或超过总期限不能驳回',()=>{assert.throws(()=>policy.requireRework({result:'驳回',note:'补充'}),/整改/);assert.throws(()=>policy.requireRework({result:'驳回',note:'补充',rectifyDue:policy.addDays(policy.businessDay(),3)},policy.addDays(policy.businessDay(),2)),/总期限/);});
test('普通审批期限初始化一次，读取不滚动延长',()=>{const f=fixture();f.s.requests=[{id:'r',status:'待审批',job:'设计',count:1,center:'视觉内容中心',reason:'补位'}];f.put(f.s);const x=f.run('crossApprovals()[0]');const d=f.read();d.requests[0].workflow.nodes.requestReview.due='2026-09-01';f.put(d);assert.equal(f.run('crossApprovals()[0].nodeDue'),'2026-09-01');assert.equal(f.run('crossApprovals()[0].nodeDue'),'2026-09-01');assert.ok(x.totalDue);});
test('公共待办调薪完整结案与员工档案同步，不只改流程标记',async()=>{const f=fixture();const e=f.s.employees[4];e.status='在职';const p=engine.makeProcess(f.s,e,'调薪',engine.day(),{salary:12345});f.put(f.s);for(let n=0;n<p.tasks.length;n++){const rows=f.run('crossApprovals()'),x=rows.find(x=>!x.done);assert.ok(x);f.c.role=x.center;f.c.level=['人事专员','员工本人'].includes(x.owner)?'员工':'负责人';f.c.employeeId=x.employeeId||'emp-3-2';await f.run(`crossReview(${JSON.stringify(x.key)},'通过','核验依据')`);}assert.equal(f.read().employees.find(x=>x.id===e.id).salary,12345);assert.ok(f.read().processes[0].closed);assert.equal(f.run('crossApprovals().filter(x=>x.done).length'),1);});
test('员工本人只派给对应员工，同阶段必要事项同时出现',()=>{const f=fixture();const e=f.s.employees[1];f.s.processes=[{id:'p',type:'离职',employeeId:e.id,created:engine.day(),payload:{},tasks:[{id:'1',stage:'结清',title:'员工确认',owner:'员工本人',due:engine.day(),done:false},{id:'2',stage:'结清',title:'结算',owner:'财务风控',due:engine.day(),done:false}]}];f.put(f.s);assert.equal(f.run('crossApprovals().length'),2);const x=f.run('crossApprovals()[0]');assert.equal(x.center,2);f.c.role=2;f.c.level='员工';f.c.employeeId='hr-'+e.id;assert.equal(f.run('crossVisible(crossApprovals()[0])'),true);f.c.employeeId='someone-else';assert.equal(f.run('crossVisible(crossApprovals()[0])'),false);});
test('公共入口的制度发布保留版本冲突检查并生成签收',async()=>{const f=fixture();const r=ops.command(f.s,'docSubmit',{title:'制度',category:'制度规范',reason:'新增',content:'有效正文',recipients:['emp-5']},'人事专员');f.put(f.s);f.c.role=0;const x=f.run('crossApprovals()[0]');await f.run(`crossReview(${JSON.stringify(x.key)},'通过','核验正文')`);assert.equal(f.read().receipts.length,1);assert.equal(f.read().documents[0].versions[0].content,'有效正文');const d=f.read();const old=d.documents[0];const r2=ops.command(d,'docSubmit',{docId:old.id,title:old.title,category:old.category,reason:'更新',content:'第二版'},'人事专员');old.versions.push({version:2});f.put(d);const y=f.run('crossApprovals().find(x=>x.sourceId==='+JSON.stringify(r2.id)+')');await assert.rejects(f.run(`crossReview(${JSON.stringify(y.key)},'通过','核验')`),/版本已更新/);});
test('创业者物资公共审批会真实预留库存，重复申请不能占用',async()=>{const f=fixture(),s=ops.migrate(engine.seed());s.founders=[{id:'f',name:'测试主理人'}];s.founderAssets=[];f.s.materials=[{id:'pc',name:'电脑',kind:'有价资产',status:'在库',quantity:1,value:100}];const a=onboarding.onboardingCommand(s,'onboardStockApply',{id:'f',materialId:'pc',quantity:1,note:'办公'},'人事专员',f.s);f.put(f.s);f.put(s,'chuangjie-founders-v1');const x=f.run('crossApprovals().find(x=>x.kind==="assetReview")');await f.run(`crossReview(${JSON.stringify(x.key)},'通过','库存核对')`);assert.equal(f.read().materials[0].reservation,a.id);assert.equal(f.read('chuangjie-founders-v1').founderAssets[0].status,'待派发');});
test('公共销售审批保留无需入账选项，需入账结案必须填凭证号',async()=>{const f=fixture();f.s.materials=[{id:'m',name:'旧电脑',quantity:1,status:'销售处理中'}];f.s.sales=[{id:'sale',materialId:'m',name:'旧电脑',quantity:1,status:'财务审核',date:engine.day(),history:[]}];f.put(f.s);f.c.role=4;let x=f.run('crossApprovals()[0]');await f.run(`crossReview(${JSON.stringify(x.key)},'通过','核验',{accounting:'无需入账'})`);assert.equal(f.read().sales[0].accounting,'无需入账');let d=f.read();d.sales[0].status='财务结案';d.sales[0].accounting='需入账';f.put(d);x=f.run('crossApprovals().find(x=>!x.done)');await assert.rejects(f.run(`crossReview(${JSON.stringify(x.key)},'通过','核验')`),/凭证号/);});
test('跨部门驳回后先由人事整改，再提交原审批人',async()=>{const f=fixture();const e=f.s.employees[1];f.s.processes=[{id:'p',type:'调薪',employeeId:e.id,payload:{salary:9000},tasks:[{id:'t',key:'approval',stage:'审批',title:'调薪审批',owner:'财务风控',due:policy.addDays(engine.day(),5),done:false}]}];f.put(f.s);f.c.role=4;let x=f.run('crossApprovals()[0]');await f.run(`crossReview(${JSON.stringify(x.key)},'驳回','缺少依据',{rectifyDue:${JSON.stringify(policy.addDays(engine.day(),2))}})`);x=f.run('crossApprovals()[0]');assert.equal(x.owner,'人事专员');assert.equal(x.rework.status,'待整改');f.c.role=3;f.c.level='员工';await f.run(`crossReview(${JSON.stringify(x.key)},'通过','已补齐说明')`);x=f.run('crossApprovals()[0]');assert.equal(x.owner,'财务风控');assert.equal(x.rework,null);});
test('制度关键内容和新模板归总经理，日常维护和签署归档归发展总监',()=>{assert.equal(policy.docReviewer({category:'制度规范',baseVersion:1,changeLevel:'一般维护'}),'创业发展总监');assert.equal(policy.docReviewer({kind:'template',baseVersion:0,changeLevel:'一般维护'}),'总经理');assert.equal(policy.docReviewer({subject:'f',category:'经营合作协议'}),'创业发展总监');});

test('销售驳回进入人事整改待办，重提保持原总期限并重新锁定库存',async()=>{const f=fixture();f.s.materials=[{id:'m',name:'测试电脑',quantity:1,status:'在库',value:100}];const x=ops.command(f.s,'saleSubmit',{materialId:'m',quantity:1,remaining:20,reason:'测试处理',actorIdentity:{personId:'emp-3-2'}},'人事专员');const total=x.workflow.totalDue;f.put(f.s);f.c.role=4;const row=f.run('crossApprovals()[0]');await f.run(`crossReview(${JSON.stringify(row.key)},'驳回','补充依据',{rectifyDue:${JSON.stringify(policy.addDays(engine.day(),2))}})`);f.c.role=3;f.c.level='员工';assert.equal(f.run('crossApprovals()[0].businessRework'),true);const d=f.read();ops.command(d,'saleResubmit',{id:x.id,remaining:15,note:'补齐依据',actorIdentity:{personId:'emp-3-2'}},'人事专员');assert.equal(d.sales[0].workflow.totalDue,total);assert.equal(d.materials[0].status,'销售处理中');assert.equal(d.sales[0].status,'财务审核');});
