import test from 'node:test';
import assert from 'node:assert/strict';
import {seed,day,add,newEmployee,finishTask,makeProcess,publish,advanceCandidate,convert,tick,canTask} from './engine.js';
const now=day();
const input={name:'测试员工',center:'创业者发展中心',job:'运营',start:now,probation:add(now,90),contractEnd:add(now,730),salary:9000};
function complete(s,p,date=now){for(const t of p.tasks){if(!t.done)finishTask(s,p.id,t.id,t.owner,'测试凭证编号 HR-001',date,{social:'已参保'});}}
test('35人种子数据，首次计算异常升级，再次运行不重复',()=>{const s=seed(now);assert.equal(s.employees.length,35);assert.ok(s.escalations.length>0);const n=s.events.length;tick(s,now);assert.equal(s.events.length,n);assert.ok(s.escalations.some(x=>x.target==='管理层 / 财务风控'));});
test('入职门禁：前置、角色、证据均不可绕过；未参保不能完成',()=>{const s=seed(now),e=newEmployee(s,input,'人事专员',now),p=s.processes.find(p=>p.employeeId===e.id);const t=p.tasks[5];assert.throws(()=>finishTask(s,p.id,t.id,t.owner,'证明',now),/前置/);assert.throws(()=>finishTask(s,p.id,p.tasks[0].id,'员工本人','证明'),/须由/);assert.throws(()=>finishTask(s,p.id,p.tasks[0].id,'人事专员',' '),/依据/);for(const t of p.tasks.slice(0,14))finishTask(s,p.id,t.id,t.owner,'证明',now);const social=p.tasks.find(t=>t.key==='social');assert.throws(()=>finishTask(s,p.id,social.id,'人事专员','自愿放弃社保',now,{social:'未参保'}),/依法参保/);assert.equal(social.done,false);assert.equal(p.closed,null);complete(s,p);assert.ok(p.closed);assert.equal(e.social,'已参保');assert.equal(e.status,'试用期');assert.equal(s.processes.filter(p=>p.employeeId===e.id&&p.type==='转正').length,1);});
test('未来到岗、提前转正受到日期约束',()=>{const s=seed(now);const e=newEmployee(s,{...input,start:add(now,5)},'人事专员');const p=s.processes.find(p=>p.employeeId===e.id);for(const t of p.tasks.slice(0,5))finishTask(s,p.id,t.id,t.owner,'证明');assert.throws(()=>finishTask(s,p.id,p.tasks[5].id,'人事专员','证明'),/尚未到/);const probation=s.processes.find(p=>p.employeeId===s.employees[0].id&&p.type==='转正');for(const t of probation.tasks.slice(0,3))finishTask(s,probation.id,t.id,t.owner,'证明');assert.throws(()=>finishTask(s,probation.id,probation.tasks[3].id,'人事专员','证明'),/生效日/);});
test('离职必须先交接、回收权限、归还资产、结算才能归档',()=>{const s=seed(now),e=s.employees[4],p=makeProcess(s,e,'离职');const last=p.tasks.at(-1);assert.throws(()=>finishTask(s,p.id,last.id,'人事专员','证明'),/前置/);complete(s,p);assert.equal(e.status,'已离职');assert.equal(e.access,'已回收');assert.equal(e.asset,'已归还');assert.ok(p.closed);});
test('薪酬审批完成前不修改，全部完成后更新',()=>{const s=seed(now),e=s.employees[4],old=e.salary,p=makeProcess(s,e,'调薪',now,{salary:16000});for(const t of p.tasks.slice(0,-1))finishTask(s,p.id,t.id,t.owner,'批准');assert.equal(e.salary,old);const t=p.tasks.at(-1);finishTask(s,p.id,t.id,t.owner,'执行');assert.equal(e.salary,16000);});
test('招聘阶段权限、录用转换与幂等',()=>{const s=seed(now),c=s.candidates[1];assert.throws(()=>convert(s,c.id,input,'人事专员'),/必须完成/);const rr=['人事专员','直属上级','直属上级','创业发展总监'];for(const role of rr)advanceCandidate(s,c.id,role,'测试评价');const e=convert(s,c.id,input,'人事专员');assert.equal(e.name,c.name);assert.ok(s.processes.some(p=>p.employeeId===e.id&&p.type==='入职'));assert.throws(()=>convert(s,c.id,input,'人事专员'),/不可重复/);});
test('异常解决保留历史，并且日期变化能够产生新提醒',()=>{const s=seed(now),e=s.employees[0];e.social='已参保';tick(s);assert.ok(s.escalations.find(x=>x.key===`social-${e.id}`).resolved);const n=s.escalations.length;tick(s,add(now,15));assert.ok(s.escalations.length>n);});

test('离职归档终止未完流程，不能通过旧转正流程恢复在职',()=>{const s=seed(now),e=s.employees[0],old=s.processes.find(p=>p.employeeId===e.id),exit=makeProcess(s,e,'离职');complete(s,exit);assert.ok(old.cancelled);assert.ok(old.closed);assert.throws(()=>finishTask(s,old.id,old.tasks[0].id,'直属上级','评价'),/已经完成/);assert.throws(()=>makeProcess(s,e,'转正'),/已离职/);assert.equal(e.status,'已离职');});
