import test from 'node:test';
import assert from 'node:assert/strict';
import {seed,day,add} from './engine.js';
import {migrate,command} from './operations.js';
const file={id:'test-file',name:'test.txt',size:8};
function state(){const s=migrate(seed());s.founders=[{id:'f1',name:'创业测试人',job:'事业主理人',project:'测试店铺',status:'测试',setupStatus:'待办理',history:[]}];return s;}
test('立项生成独立创业者档案，只有测试和正式状态，不添加员工',()=>{const s=state(),n=s.employees.length;const need=command(s,'founderNeed',{title:'银器项目',reason:'招募主理人'},'创业发展总监');const c=command(s,'founderCandidate',{needId:need.id,name:'新人',channel:'招聘平台',relation:'投资合作',job:'店铺主理人',project:'新店'},'人事专员');for(const role of ['人事专员','人事专员','创业发展总监','人事专员','创业发展总监','总经理'])command(s,'founderAdvance',{id:c.id,result:'通过',note:'演示核验',files:[file]},role);assert.equal(s.founders[0].status,'测试');assert.equal(s.founders[0].job,'店铺主理人');assert.equal(s.founders[0].project,'新店');assert.equal(s.employees.length,n);});
test('办公资产必须审核后派发，归还保留证据，不修改行政库存',()=>{const s=state();const a=command(s,'founderAssetApply',{founderId:'f1',name:'电脑',code:'F-A001',value:4000,note:'项目办公'},'人事专员');assert.equal(a.status,'待审核');assert.throws(()=>command(s,'founderAssetDeliver',{id:a.id,note:'领取',files:[file]},'人事专员'),/状态/);assert.throws(()=>command(s,'founderAssetReview',{id:a.id,result:'通过',note:'同意'},'人事专员'),/总监/);command(s,'founderAssetReview',{id:a.id,result:'通过',note:'同意'},'创业发展总监');command(s,'founderAssetDeliver',{id:a.id,note:'已领取',files:[file]},'人事专员');assert.equal(a.status,'使用中');assert.equal(s.materials.length,0);command(s,'founderAssetReturn',{id:a.id,note:'已归还',files:[file]},'人事专员');assert.equal(a.status,'已归还');assert.equal(a.returnFiles.length,1);});
test('按期达标申请正式，驳回不变状态，总经理批准后正式',()=>{const s=state();command(s,'founderTestPlan',{id:'f1',goal:'完成销售验证',due:add(day(),30),budget:5000},'创业发展总监');assert.throws(()=>command(s,'founderFormalSubmit',{id:'f1',rate:80,note:'未达标',budget:50000,files:[file]},'创业发展总监'),/100%/);const v={id:'f1',rate:100,note:'达标证据',budget:50000,files:[file]};command(s,'founderFormalSubmit',v,'创业发展总监');assert.equal(s.founders[0].status,'测试');command(s,'founderFormalReview',{id:'f1',result:'驳回',note:'补充说明'},'总经理');assert.equal(s.founders[0].status,'测试');command(s,'founderFormalSubmit',v,'创业发展总监');command(s,'founderFormalReview',{id:'f1',result:'通过',note:'核验通过'},'总经理');assert.equal(s.founders[0].status,'正式');assert.equal(s.founders[0].formalHistory.length,1);});
