import test from 'node:test';
import assert from 'node:assert/strict';
import {seed,day,add} from './engine.js';
import {migrate,command} from './operations.js';
import {onboardingCommand as run,onboardingStatus} from './onboarding.js';
const file={id:'evidence',name:'演示凭证.txt',size:5};
function fixture(){const s=migrate(seed());s.founders=[{id:'f',name:'演示创业者',job:'主理人',project:'店铺',status:'测试'}];s.documents=[];const admin={materials:[{id:'pc',name:'电脑',code:'XZ001',kind:'有价资产',quantity:1,value:5000,status:'在库'},{id:'paper',name:'纸巾',code:'XZ002',kind:'易耗品',quantity:10,value:5,status:'在库'}],movements:[]};return {s,admin};}
test('账号与档案须审核，四项全部完成才消除待办',()=>{const {s,admin}=fixture();const base={id:'f',note:'核验依据'};assert.equal(onboardingStatus(s,s.founders[0]).filter(t=>!t.done).length,4);run(s,'onboardAccountSubmit',{...base,account:'demo',permissions:'项目运营',scope:'自己的店铺'},'人事专员');assert.throws(()=>run(s,'onboardAccountActivate',base,'人事专员'));run(s,'onboardAccountReview',{...base,result:'通过'},'创业发展总监');run(s,'onboardAccountActivate',base,'人事专员');run(s,'onboardProfileSubmit',{...base,job:'主理人',project:'新店',contact:'演示联系方式',start:'2026-09-26',background:'演示履历'},'人事专员');run(s,'onboardProfileReview',{...base,result:'通过'},'创业发展总监');for(const category of ['经营合作协议','创界平台服务协议']){const r=command(s,'docSubmit',{title:category,category,subject:'f',kind:'signed',reason:'签署归档',files:[file]},'人事专员');command(s,'docReview',{id:r.id,result:'通过',note:'签署核验'},'创业发展总监');}const a=run(s,'onboardStockApply',{...base,materialId:'pc',quantity:1},'人事专员',admin);run(s,'onboardStockReview',{id:a.id,note:'同意',result:'通过'},'创业发展总监',admin);assert.equal(admin.materials[0].status,'创业者派发预留');assert.throws(()=>run(s,'onboardStockDeliver',{id:a.id,note:'领取'},'人事专员',admin));run(s,'onboardStockDeliver',{id:a.id,note:'已领取',files:[file]},'人事专员',admin);assert.equal(admin.materials[0].holder,'founder:f');assert.ok(onboardingStatus(s,s.founders[0]).every(t=>t.done));assert.throws(()=>run(s,'onboardStockDeliver',{id:a.id,note:'重复',files:[file]},'人事专员',admin));run(s,'onboardStockReturn',{id:a.id,note:'归还',files:[file]},'人事专员',admin);assert.equal(admin.materials[0].status,'在库');});
test('易耗品实际扣库，重复占用失败，模板不算签署合同',()=>{const {s,admin}=fixture();const a=run(s,'onboardStockApply',{id:'f',materialId:'paper',quantity:3,note:'办公'},'人事专员',admin);run(s,'onboardStockReview',{id:a.id,result:'通过',note:'核准'},'创业发展总监',admin);assert.throws(()=>run(s,'onboardStockApply',{id:'f',materialId:'paper',quantity:3,note:'重复'},'人事专员',admin));run(s,'onboardStockDeliver',{id:a.id,note:'收到',files:[file]},'人事专员',admin);assert.equal(admin.materials[1].quantity,7);const r=command(s,'docSubmit',{title:'经营合作模板',category:'经营合作协议',kind:'template',reason:'模板',files:[file]},'人事专员');command(s,'docReview',{id:r.id,result:'通过',note:'批准模板'},'总经理');assert.equal(s.documents[0].kind,'template');assert.equal(onboardingStatus(s,s.founders[0])[2].done,false);});
test('最终立项只能总经理批准，驳回回到项目评估',()=>{const {s}=fixture();s.founderCandidates=[{id:'c',name:'候选人',stage:5,status:'跟进中',history:[]}];assert.throws(()=>command(s,'founderAdvance',{id:'c',result:'通过',note:'同意'},'创业发展总监'),/总经理/);command(s,'founderAdvance',{id:'c',result:'驳回',note:'补充计划',rectifyDue:add(day(),2)},'总经理');assert.equal(s.founderCandidates[0].stage,4);assert.equal(s.founders.length,1);});
