import test from 'node:test';
import assert from 'node:assert/strict';
import {seed,day,add,finishTask,makeProcess,advanceCandidate,publish} from './engine.js';
import {command,migrate,ready} from './operations.js';
const file={id:'fixture',name:'测试凭证.txt',size:12,type:'text/plain'};
function run(s,a,v,r){const draft=structuredClone(s),out=command(draft,a,v,r);Object.assign(s,draft);return out;}
const review={result:'通过',note:'已核验演示依据'};
function stock(s,kind='有价资产',quantity=2){let p=run(s,'purchaseSubmit',{name:'测试电脑',kind,quantity,value:3000,years:kind==='有价资产'?3:0,reason:'工作使用'},'人事专员');run(s,'purchaseReview',{id:p.id,...review},'财务负责人');run(s,'purchaseReceive',{id:p.id,note:'已收货',files:[file]},'人事专员');run(s,'purchaseConfirm',{id:p.id,...review},'创业发展总监');return s.materials;}
test('招聘取消Offer，旧Offer迁移为待入职，录用审批后可转换',()=>{const s=migrate(seed());const c=s.candidates[1];for(const role of ['人事专员','直属上级','直属上级','创业发展总监'])advanceCandidate(s,c.id,role,'核验');assert.equal(c.stage,'待入职');c.stage='Offer';migrate(s);assert.equal(c.stage,'待入职');assert.ok(c.history.some(h=>h.stage==='流程调整'));});
test('上传更新审批前版本不变，非管理层不可审批，批准后独立签收',()=>{const s=migrate(seed());const req=run(s,'docSubmit',{docId:'doc-2',title:'员工手册',category:'制度规范',reason:'更新',files:[file],recipients:['emp-5']},'人事专员');assert.equal(s.documents[2].versions.length,1);assert.equal(s.receipts.length,0);assert.throws(()=>run(s,'docReview',{id:req.id,...review},'创业发展总监'),/总经理/);assert.throws(()=>publish(s,'doc-2','绕过审批',[],'创业发展总监'),/审批/);run(s,'docReview',{id:req.id,...review},'总经理');assert.equal(s.documents[2].versions.length,2);assert.equal(s.receipts[0].version,2);assert.equal(s.documents[2].versions[1].files[0].id,'fixture');assert.throws(()=>run(s,'docReview',{id:req.id,...review},'总经理'),/状态/);});
test('文件驳回保留旧版，修改重提形成新审批记录',()=>{const s=migrate(seed());let req=run(s,'docSubmit',{title:'行政办法',category:'制度规范',reason:'新建',content:'第一版',recipients:[]},'人事专员');run(s,'docReview',{id:req.id,result:'驳回',note:'请补充',rectifyDue:add(day(),2)},'总经理');const fresh=run(s,'docSubmit',{resubmit:req.id,title:req.title,category:req.category,reason:'补充',content:'完整版本'},'人事专员');assert.equal(s.docRequests.find(x=>x.id===req.id).status,'已重提');run(s,'docReview',{id:fresh.id,...review},'总经理');assert.equal(s.documents[0].title,'行政办法');assert.equal(s.documents[0].versions.length,1);});
test('财务和上级全部通过才入库，重复确认不重复库存',()=>{const s=migrate(seed());stock(s);assert.equal(s.materials.length,2);assert.equal(s.materials[0].quantity,1);assert.throws(()=>run(s,'purchaseConfirm',{id:s.purchases[0].id,...review},'创业发展总监'),/状态/);assert.equal(s.materials.length,2);});
test('资产领用、换发、归还与离职检查联动',()=>{const s=migrate(seed());stock(s);const [a,b]=s.materials;run(s,'issue',{id:a.id,holder:'emp-5',quantity:1,note:'交付'},'人事专员');const p=makeProcess(s,s.employees[4],'离职');for(const t of p.tasks.slice(0,3))finishTask(s,p.id,t.id,t.owner,'依据');assert.throws(()=>finishTask(s,p.id,p.tasks[3].id,'人事专员','归还'),/未归还/);run(s,'replace',{id:a.id,replacement:b.id,damaged:'是',note:'更换损坏电脑'},'人事专员');assert.equal(s.materials.find(m=>m.id===a.id).status,'损坏待处理');assert.equal(s.materials.find(m=>m.id===b.id).holder,'emp-5');run(s,'return',{id:b.id,damaged:'否',note:'已归还'},'人事专员');finishTask(s,p.id,p.tasks[3].id,'人事专员','仓库已确认');});
test('易耗品派发扣减库存且不挂领用人，超量禁止',()=>{const s=migrate(seed());stock(s,'易耗品',10);const m=s.materials[0];run(s,'issue',{id:m.id,holder:'emp-5',quantity:4,note:'发纸巾'},'人事专员');assert.equal(s.materials[0].quantity,6);assert.equal(s.materials[0].holder,'');assert.throws(()=>run(s,'issue',{id:m.id,holder:'emp-5',quantity:7,note:'超量'},'人事专员'),/库存不足/);});
test('销售锁定库存，财务决定入账，记录销售后凭证结案',()=>{const s=migrate(seed());stock(s);const m=s.materials[0];const sale=run(s,'saleSubmit',{materialId:m.id,quantity:1,remaining:500,reason:'损坏处理'},'人事专员');assert.equal(s.materials[0].status,'销售处理中');run(s,'saleReview',{id:sale.id,...review,accounting:'需入账'},'财务负责人');run(s,'saleExecute',{id:sale.id,price:400,note:'已售',files:[file]},'人事专员');assert.throws(()=>run(s,'saleClose',{id:sale.id,note:'已核验'},'财务负责人'),/凭证号/);run(s,'saleClose',{id:sale.id,note:'已核验',voucher:'JZ-1'},'财务负责人');assert.equal(s.materials[0].status,'已售出');});
test('创业招募计划书必传，立项转主理人，不重复建立',()=>{const s=migrate(seed());const n=run(s,'founderNeed',{title:'茶器主理人',reason:'新项目'},'创业发展总监');const c=run(s,'founderCandidate',{needId:n.id,name:'测试合作人',channel:'招聘平台',relation:'投资合作'},'人事专员');for(const role of ['人事专员','人事专员','创业发展总监'])run(s,'founderAdvance',{id:c.id,...review},role);assert.throws(()=>run(s,'founderAdvance',{id:c.id,...review},'人事专员'),/计划书/);run(s,'founderAdvance',{id:c.id,...review,files:[file]},'人事专员');for(const role of ['创业发展总监','总经理'])run(s,'founderAdvance',{id:c.id,...review},role);assert.equal(s.founders.length,1);assert.throws(()=>run(s,'founderAdvance',{id:c.id,...review},'创业发展总监'),/状态/);});
test('协议审批和手续门禁，项目GM审批、月评和下一阶段预算',()=>{const s=migrate(seed());const f=run(s,'employeeFounder',{employeeId:'emp-5'},'人事专员');const v={founderId:f.id,title:'测试项目',shop:'测试店铺',license:'演示主体',phases:[0,1,2].map(i=>({goal:'阶段目标'+i,due:add(day(),30*(i+1)),budget:10000*(i+1)}))};assert.throws(()=>run(s,'ventureSubmit',v,'创业发展总监'),/协议/);for(const category of ['经营合作协议','创界平台服务协议']){const d=run(s,'docSubmit',{subject:f.id,title:category,category,reason:'签署归档',files:[file]},'人事专员');run(s,'docReview',{id:d.id,...review},'创业发展总监');}run(s,'founderSetup',{id:f.id,note:'无需派发物资，手续完整',files:[file]},'人事专员');run(s,'founderSetupReview',{id:f.id,...review},'创业发展总监');assert.ok(ready(s,s.founders[0]));const p=run(s,'ventureSubmit',v,'创业发展总监');assert.throws(()=>run(s,'ventureReview',{id:p.id,...review},'管理层'),/总经理/);run(s,'ventureReview',{id:p.id,...review},'总经理');assert.equal(s.ventures[0].releasedPhase,0);assert.throws(()=>run(s,'fundingSubmit',{id:p.id,note:'申请资金'},'创业发展总监'),/100%/);run(s,'ventureMonth',{id:p.id,month:day().slice(0,7),phase:0,used:8000,rate:100,note:'达到目标',files:[file]},'创业发展总监');run(s,'fundingSubmit',{id:p.id,note:'申请阶段二'},'创业发展总监');run(s,'fundingReview',{id:p.id,fundingId:s.ventures[0].funding[0].id,...review},'总经理');assert.equal(s.ventures[0].releasedPhase,1);});
