import {docReviewer,businessDay,addDays} from './workflow-policy.js';
import {onboardingStatus} from './onboarding.js';
import {command,migrate,recipients,ready,remaining,recruiterStages} from './operations.js';
import {day} from './engine.js';
let warehouseTab='stock',warehouseQuery='',warehouseFilter='全部',recruitTab='candidates',recruitQuery='',recruitStage='全部';
let documentTab='library',documentQuery='',peopleQuery='',peopleOnlyPending=false;
let ctx,docFilter='全部',agreementTab='templates',agreementQuery='',agreementCategory='全部',agreementStatus='全部';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const s=()=>migrate(ctx.state()),r=()=>ctx.role();
const button=(label,action,id='',allowed=[])=>`<button class="secondary compact" data-op="${action}" data-id="${esc(id)}" ${allowed.length&&!allowed.includes(r())?'disabled':''}>${label}</button>`;
const field=(name,label,type='text',value='',extra='')=>`<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra} required></label>`;
const area=(name,label,value='',required=true)=>`<label class="field">${label}<textarea name="${name}" ${required?'required':''}>${esc(value)}</textarea></label>`;
const select=(name,label,options,value='')=>`<label class="field">${label}<select name="${name}" required>${options.map(o=>{const [v,l]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(l)}</option>`;}).join('')}</select></label>`;
const upload='<label class="field">上传文件（可多选，单文件不超过 10 MB）<input type="file" name="files" multiple></label>';
const note=()=>area('note','处理意见 / 依据');
const review=()=>select('result','审批结果',['通过','驳回'])+note()+field('rectifyDue','驳回时的整改期限','date',addDays(businessDay(),2),'min="'+businessDay()+'"');
const title=(h,p,a='')=>`<div class="page-heading"><div><h1>${h}</h1><p>${p}</p></div><div class="actions">${a}</div></div>`;
const table=(headers,rows)=>`<section class="panel"><div class="table-scroll"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}">暂无记录</td></tr>`}</tbody></table></div></section>`;
const row=(...cells)=>`<tr>${cells.map(c=>`<td>${c}</td>`).join('')}</tr>`;
const names=id=>s().materials.find(m=>m.holder===id)?.holderName||s().movements.find(m=>m.holder===id)?.person||recipients(s()).find(x=>x.id===id)?.name||s().founders.find(f=>f.id===id)?.name||'—';
const labels={onboardAccountSubmit:'提交账号权限申请',onboardAccountReview:'审核账号权限',onboardAccountActivate:'确认账号开通',onboardProfileSubmit:'提交创业者档案',onboardProfileReview:'审核创业者档案',onboardStockApply:'申请行政物资',onboardStockReview:'审核并预留物资',onboardStockDeliver:'确认领取出库',onboardStockReturn:'归还行政物资',founderProfile:'维护创业者档案',founderTestPlan:'设置测试目标',founderFormalSubmit:'提交正式评估',founderFormalReview:'审核正式评估',founderAssetApply:'申请办公资产',founderAssetReview:'审核资产派发',founderAssetDeliver:'确认派发',founderAssetReturn:'归还资产',purchaseReview:'财务审核采购',purchaseReceive:'登记采购到货',purchaseConfirm:'上级确认入库',issue:'物资派发',return:'资产归还',replace:'资产换发',damage:'标记损坏',saleReview:'财务审核销售',saleExecute:'登记销售结果',saleClose:'财务入账结案',founderNeed:'建立招募需求',founderCandidate:'登记候选人',founderAdvance:'招募步骤办理',employeeFounder:'员工登记事业主理人',founderSetup:'提交人事手续',founderSetupReview:'审核人事手续',ventureSubmit:'提交项目申请',ventureReview:'总经理审核项目',ventureMonth:'更新月度评估',fundingSubmit:'申请阶段预算',fundingReview:'总经理审批阶段预算'};
const hist=x=>`<h3>办理记录</h3>${(x.history||[]).map(h=>`<div class="version"><b>${esc(labels[h.action]||h.action||h.stage)} · ${esc(h.role)}</b><small>${esc(new Date(h.time).toLocaleString('zh-CN'))}</small><p>${esc(h.note)}</p></div>`).join('')||'<p>暂无办理记录</p>'}`;
const files=xs=>(xs||[]).map(f=>button('下载 '+esc(f.name),'download',f.id)).join(' ');
function db(){return new Promise((resolve,reject)=>{const q=indexedDB.open('chuangjie-hr-files',1);q.onupgradeneeded=()=>q.result.createObjectStore('files',{keyPath:'id'});q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(Error('文件存储不可用'));});}
async function storeFiles(list){const result=[];for(const f of list){if(!f.size)continue;if(f.size>10*1024*1024)throw Error('单个文件不得超过10MB');const id=crypto.randomUUID(),d=await db();await new Promise((resolve,reject)=>{const tx=d.transaction('files','readwrite');tx.objectStore('files').put({id,blob:f});tx.oncomplete=resolve;tx.onerror=()=>reject(Error('文件保存失败'));});d.close();result.push({id,name:f.name,size:f.size,type:f.type});}return result;}
async function download(id){const all=[...s().documents.flatMap(d=>d.versions.flatMap(v=>v.files||[])),...s().docRequests.flatMap(x=>x.files||[]),...s().purchases.flatMap(x=>x.files||[]),...s().sales.flatMap(x=>x.files||[]),...s().founderCandidates.flatMap(x=>x.planFiles||[]),...s().founders.flatMap(x=>[...(x.setupFiles||[]),...(x.formalReview?.files||[]),...(x.profile?.files||[]),...(x.profileHistory||[]).flatMap(p=>p.files||[])]),...s().founderAssets.flatMap(x=>[...(x.files||[]),...(x.returnFiles||[])]),...s().ventures.flatMap(x=>x.months.flatMap(m=>m.files||[]))];const meta=all.find(f=>f.id===id);if(!meta)throw Error('附件不存在');const d=await db(),record=await new Promise((resolve,reject)=>{const q=d.transaction('files').objectStore('files').get(id);q.onsuccess=()=>resolve(q.result);q.onerror=reject;});d.close();if(!record)throw Error('本浏览器没有该附件，请使用原上传浏览器');const a=document.createElement('a');a.href=URL.createObjectURL(record.blob);a.download=meta.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function form(label,action,id,body,extra=''){if(!id&&/Submit$|founderCandidate$|founderNeed$|onboardStockApply$/.test(action))body+=field('totalDue','流程总截止日期','date',addDays(businessDay(),14),'min="'+businessDay()+'"')+'<p class="sub">请按本事项确认总期限；普通审批默认2个自然日，各节点不超过总期限。</p>';if(action==='docSubmit'&&!body.includes('founder-steps'))body=flowStrip([['上传或更新文件','人事专员'],['管理层审核','管理层'],['发布生效','系统']],0)+body;if(action==='purchaseSubmit')body='<p class="form-intro">填写物资规格和采购预算，提交后由财务审核。</p>'+body+'<div class="purchase-estimate">预计采购总额 <strong id="purchase-total">待填写数量与单价</strong><small>有价资产逐件编码；易耗品按数量管理。</small></div>';ctx.panel(label,`${formFlowContext(action,id)}${operationContext(action,id)}<form data-op-form="${action}" data-id="${esc(id||'')}" ${extra}><div class="form-grid">${body}</div><p class="form-error" role="alert"></p><div class="form-footer"><button type="submit" class="primary">${({docSubmit:'提交管理层审批',purchaseSubmit:'提交财务审核',purchaseReview:'提交审核结果',purchaseReceive:'提交到货记录',purchaseConfirm:'确认处理结果',saleSubmit:'提交财务审核',founderNeed:'发布用人需求',founderCandidate:'保存候选人',founderAdvance:'提交本步骤结果'})[action]||'确认提交'}</button></div></form>`,true);}
export function documentsPage(scope=''){if(scope==='agreements')return agreementsPage();const docs=s().documents.filter(d=>!d.subject&&d.kind!=='template'),requests=s().docRequests.filter(r=>!r.subject&&r.kind!=='template'),matched=docs.filter(d=>!documentQuery||[d.title,d.category].join(' ').includes(documentQuery));return title('制度与档案','统一维护有效文件，新增与更新审批后发布。',button('＋ 上传 / 新建文件','docNew','',['人事专员','创业发展总监']))+metrics([['生效文件',docs.length,'保留历史版本'],['待审批',requests.filter(x=>x.status==='待审批').length,'管理层审核后发布'],['待签收',s().receipts.filter(x=>!x.signedAt).length,'按版本跟踪签收'],['已驳回',requests.filter(x=>x.status==='已驳回').length,'补充后重新提交']])+`<section class="work-library"><div class="agreement-tabs">${[['library','有效文件',docs.length],['reviews','新增与更新审批',requests.length],['receipts','签收记录',s().receipts.length]].map(([key,t,n])=>`<button data-op="documentTab" data-id="${key}" aria-selected="${documentTab===key}">${t} <span>${n}</span></button>`).join('')}</div>${documentTab==='library'?`<div class="work-toolbar"><label>查找文件<input id="document-query" placeholder="文件名称或分类" value="${esc(documentQuery)}"></label>${button('查询','documentSearch')}${button('重置','documentReset')}</div><div class="agreement-grid">${matched.map(d=>`<article class="agreement-card"><div class="agreement-card-top"><span class="agreement-file-icon">▤</span>${chip('已生效')}</div><small>${esc(d.category||'制度文件')}</small><h3>${esc(d.title)}</h3><div class="agreement-meta"><span>当前版本<b>V${d.versions.length}</b></span><span>生效日期<b>${esc(d.versions.at(-1)?.date||'—')}</b></span></div><div class="agreement-card-actions">${button('查看版本与文件','docVersion',d.id)}${button('申请更新','docEdit',d.id,['人事专员','创业发展总监'])}</div></article>`).join('')||emptyBlock('暂无匹配文件','可调整搜索或上传新文件。')}</div>`:documentTab==='reviews'?`<div class="doc-filters work-inner">${['全部','待审批','已驳回','已通过'].map(k=>`<button data-op="docFilter" data-id="${k}" class="${docFilter===k?'primary':'secondary'}">${k} ${requests.filter(x=>k==='全部'||x.status===k).length}</button>`).join('')}</div>`+table(['文件名称','分类','申请日期','状态','操作'],requests.filter(x=>docFilter==='全部'||x.status===docFilter).map(x=>row('<b>'+esc(x.title)+'</b>',esc(x.category),x.created,chip(x.status),button('查看申请 / 审批','docRequest',x.id)))):table(['员工','文件名称','版本','签收状态','操作'],s().receipts.filter(x=>docs.some(d=>d.id===x.docId)).map(x=>row(esc(names(x.employeeId)),esc(docs.find(d=>d.id===x.docId)?.title),'V'+x.version,chip(x.signedAt?'已签收':'待签收'),`<button class="secondary compact" data-action="process" data-id="${x.processId}">查看签收流程</button>`)))}</section>`;}
const money=v=>'¥'+Number(v||0).toLocaleString('zh-CN',{maximumFractionDigits:2});
const chip=(v)=>`<span class="agreement-pill ${/驳回|损坏|超期/.test(v)?'red':/待|审核|确认|采购入库|预留/.test(v)?'amber':''}">${esc(v)}</span>`;
const metrics=items=>`<div class="work-metrics">${items.map(([label,n,hint])=>`<section><small>${label}</small><strong>${n}</strong><span>${hint||''}</span></section>`).join('')}</div>`;
const emptyBlock=(label,note)=>`<div class="agreement-empty"><span>▤</span><h3>${label}</h3><p>${note}</p></div>`;
function recruitSteps(c){return flowStrip(recruiterStages.map((stage,i)=>[i===5?'总经理立项审批':stage,i===5?'总经理':i<2||i===3?'人事专员':'创业发展总监']).concat([['已立项','自动建档']]),c.status==='已立项'?6:c.stage);}
function operationContext(action,id){
 if(action==='purchaseSubmit'&&!id)return flowStrip([['采购申请','人事专员'],['财务审核','财务负责人'],['采购与到货','人事专员'],['确认入库','创业发展总监'],['已入库','系统']],0);
 if(action==='saleSubmit')return flowStrip([['申请销售','人事专员'],['财务审核','财务负责人'],['登记销售','人事专员'],['财务结案','财务负责人'],['完成','系统']],0);
 if(action==='docReview'){const d=s().docRequests.find(d=>d.id===id);return flowStrip([[d?.subject?'签署并上传':'上传或更新文件','人事专员'],['管理层审批','管理层'],['生效归档','系统']],1);}
 if(action==='founderNeed'||action==='founderCandidate')return flowStrip([['提出用人需求','创业发展总监'],['招募与候选人','人事专员'],['面谈与人员评估','人事 / 总监'],['计划书与项目评估','人事 / 总监'],['立项审批','总经理'],['人员建档与手续','人事专员']],action==='founderNeed'?0:1);
 if(action==='founderAdvance'){const c=s().founderCandidates.find(x=>x.id===id);return `<div class="work-context"><h3>${esc(c.name)} · ${esc(c.project||'创业招募')}</h3>${recruitSteps(c)}<p>本步骤办理人：${c.stage===5?'总经理':c.stage<2||c.stage===3?'人事专员':'创业发展总监'}</p></div>`;}
 if(action.startsWith('purchase')&&id){const x=s().purchases.find(x=>x.id===id);if(x)return purchaseSummary(x);}
 if(action.startsWith('sale')&&id){const x=s().sales.find(x=>x.id===id);if(x)return saleSummary(x);}
 if(['issue','return','replace','damage'].includes(action)){const m=s().materials.find(x=>x.id===id);return `<div class="work-context"><h3>${esc(m.name)} · ${esc(m.code)}</h3><p>${chip(m.status)} ${esc(m.kind)} · 可用数量 ${m.quantity} · 原值 ${money(m.value)}</p></div>`;}
 return '';}
function purchaseSummary(x){const steps=[['采购申请','人事专员'],['财务审核','财务负责人'],['采购与到货','人事专员'],['确认入库','创业发展总监'],['已入库','—']],i={'财务审核':1,'采购入库':2,'上级确认':3,'已入库':4,'已驳回':0}[x.status]??0;return `<div class="work-context"><h3>${esc(x.name)}</h3>${flowStrip(steps,i,x.status==='已驳回')}<div class="work-facts"><span>采购数量<b>${x.quantity} 件</b></span><span>单件价值<b>${money(x.value)}</b></span><span>采购总额<b>${money(x.quantity*x.value)}</b></span><span>物资类型<b>${x.kind}</b></span></div><p>采购理由：${esc(x.reason)}</p></div>`;}
function saleSummary(x){return `<div class="work-context"><h3>${esc(x.name)} · 物资销售</h3>${flowStrip([['申请销售','人事专员'],['财务审核','财务负责人'],['登记销售','人事专员'],['财务结案','财务负责人'],['完成','—']],{'财务审核':1,'待销售':2,'财务结案':3,'已完成':4,'已驳回':0}[x.status]??0,x.status==='已驳回')}<p>销售原因：${esc(x.reason)} · 数量 ${x.quantity} · 剩余价值 ${money(x.remaining)}</p></div>`;}
export function warehousePage(){
 const state=s(),stocks=state.materials,orders=state.purchases,moves=state.movements;
 const pool=warehouseTab==='stock'?stocks:warehouseTab==='purchases'?orders:moves;
 const filtered=pool.filter(x=>(warehouseFilter==='全部'||(warehouseTab==='stock'?x.status:warehouseTab==='purchases'?x.status:x.type)===warehouseFilter)&&(!warehouseQuery||[x.name,x.code,x.holder?names(x.holder):'',x.person].join(' ').includes(warehouseQuery)));
 const statuses=warehouseTab==='stock'?['在库','领用中','创业者派发预留','损坏待处理','已耗用','销售处理中','已售出']:warehouseTab==='purchases'?['财务审核','采购入库','上级确认','已入库','已驳回']:[...new Set(moves.map(x=>x.type))];
 let body;if(warehouseTab==='stock')body=table(['物资 / 编码','类型','数量','原值 / 剩余价值','状态 / 领用人','操作'],filtered.map(m=>row(`<b>${esc(m.name)}</b><small class="agreement-row-sub">${esc(m.code)}</small>`,esc(m.kind),m.quantity,money(m.value)+'<small class="agreement-row-sub">剩余 '+money(remaining(m))+' · '+m.years+' 年折价</small>',chip(m.status)+'<small class="agreement-row-sub">'+esc(names(m.holder))+'</small>',button('查看物资','material',m.id))));
 else if(warehouseTab==='purchases')body=table(['采购物资','数量 / 总额','当前环节','办理人','操作'],filtered.map(x=>row('<b>'+esc(x.name)+'</b><small class="agreement-row-sub">'+esc(x.kind)+'</small>',x.quantity+' 件 / '+money(x.quantity*x.value),chip(x.status),{'财务审核':'财务负责人','采购入库':'人事专员','上级确认':'创业发展总监','已入库':'已完成','已驳回':'人事专员'}[x.status],button('查看采购流程','purchase',x.id))));
 else body=table(['物资','办理类型','领取人','数量','日期'],filtered.map(x=>row(esc(x.name),chip(x.type),esc(x.person||names(x.holder)),x.quantity,x.date)));
 return title('行政物资仓库','从采购、入库到派发与归还，每件物资都有清晰记录。',button('物资销售','sales')+button('＋ 采购物资','purchaseNew','',['人事专员']))+metrics([['在库物资',stocks.filter(m=>m.status==='在库').reduce((n,m)=>n+m.quantity,0),'可申请派发'],['领用资产',stocks.filter(m=>m.status==='领用中').length,'按编码追踪责任人'],['采购待办',orders.filter(x=>!['已入库','已驳回'].includes(x.status)).length,'审核、到货与入库'],['损坏待处理',stocks.filter(m=>m.status==='损坏待处理').length,'查看物资后处理']])+`<section class="work-library"><div class="agreement-tabs">${[['stock','库存台账',stocks.length],['purchases','采购与入库',orders.length],['movements','派发与归还记录',moves.length]].map(([key,label,n])=>`<button data-op="warehouseTab" data-id="${key}" aria-selected="${warehouseTab===key}">${label} <span>${n}</span></button>`).join('')}</div><div class="work-toolbar"><label>搜索物资<input id="warehouse-query" value="${esc(warehouseQuery)}" placeholder="名称、编码或领用人"></label><label>办理状态<select id="warehouse-filter">${['全部',...statuses].map(x=>`<option ${x===warehouseFilter?'selected':''}>${x}</option>`).join('')}</select></label>${button('查询','warehouseSearch')}${button('重置','warehouseReset')}<span>共 ${filtered.length} 条</span></div>${filtered.length?body:emptyBlock('暂无符合条件的记录','可调整筛选；新物资需完成采购与入库流程。')}</section>`;
}
function salesPage(){const list=s().sales;return title('物资销售','财务核准后销售，完成入账或结案后更新库存。',button('返回仓库','warehouse')+button('＋ 申请销售','saleNew','',['人事专员']))+metrics([['待财务审核',list.filter(x=>x.status==='财务审核').length],['待销售',list.filter(x=>x.status==='待销售').length],['待财务结案',list.filter(x=>x.status==='财务结案').length],['已完成',list.filter(x=>x.status==='已完成').length]])+table(['物资','数量 / 剩余价值','实际售价','当前环节','操作'],list.map(x=>row('<b>'+esc(x.name)+'</b>',x.quantity+' / '+money(x.remaining),x.price==null?'待登记':money(x.price),chip(x.status),button('查看销售流程','sale',x.id))));}
export function foundersPage(){return title('创业者管理','事业主理人包括投资合作伙伴和雇佣员工，可负责多个项目。',button('＋ 招募需求','founderNeedNew','',['创业发展总监'])+button('＋ 候选人','founderCandidateNew','',['人事专员'])+button('员工登记主理人','employeeFounderNew','',['人事专员'])+button('协议档案','agreements'))+table(['招募需求','理由','状态'],s().founderNeeds.map(n=>row(esc(n.title),esc(n.reason),n.status)))+`<h2>招募跟踪</h2><p>需求 → 人事招聘 → 候选人 → 面谈 → 人员评估 → 项目计划书 → 项目评估 → 总经理立项审批</p>`+table(['候选人 / 渠道','合作关系','当前步骤','操作'],s().founderCandidates.map(c=>row(esc(c.name)+' / '+esc(c.channel),c.relation,c.status==='已立项'?'已立项':recruiterStages[c.stage],button('跟进 / 查看','founderCandidate',c.id))))+`<h2>创业者人员管理 ${s().founders.length}</h2>`+table(['事业主理人','关系','筹备情况','经营状态','操作'],s().founders.map(f=>row(esc(f.name),f.relation,ready(s(),f)?'协议、手续已完成':'待完善协议 / 手续',f.status,button('人员档案','founder',f.id))));}
export function venturesPage(){return title('项目全流程管理','筹备完成后建项目，总经理批准首阶段预算；按月跟踪，达标后申请下一阶段资金。',button('＋ 建立项目','ventureNew','',['创业发展总监']))+table(['项目 / 负责人','店铺 / 营业执照','状态','已批准阶段 / 预算','操作'],s().ventures.map(p=>row(esc(p.title)+' / '+esc(names(p.founderId)),esc(p.shop||'—')+' / '+esc(p.license||'—'),p.status,p.releasedPhase<0?'未批准':'第'+(p.releasedPhase+1)+'阶段 / ¥'+p.phases.slice(0,p.releasedPhase+1).reduce((n,x)=>n+x.budget,0),button('项目档案','venture',p.id))));}
function docForm(d,previous,subject,kind=''){kind=d?.kind||previous?.kind||kind;const p=previous||{},latest=d?.versions.at(-1);form('文件新增 / 更新申请','docSubmit',d?.id,((subject||d?.subject)?flowStrip([['签署并上传','人事专员'],['签署文件审核','管理层'],['生效归档','—']],0):'')+field('title','文件名称', 'text',p.title||d?.title||'')+select('category','分类',subject||d?.subject||kind==='template'?((subject||d?.subject)&&(p.category||d?.category)?[p.category||d.category]:['经营合作协议','创界平台服务协议']):['制度规范','合同协议','培训材料','行政档案'],p.category||d?.category)+select('changeLevel','变更性质',['关键内容','一般维护'],p.changeLevel||'关键内容')+`<p class="notice">制度与合同模板新增或关键内容变更由总经理审核；排版、错字等一般维护及签署协议归档由发展中心总监审核。</p>`+area('reason','新增 / 更新原因',p.reason||'')+area('content','完整内容（可用上传文件代替）',p.content||latest?.content||'',false)+upload+((p.files||latest?.files)?.length?`<p>未选择新文件时保留原附件；选择新文件会替换本次附件，旧版仍可下载。</p>${files(p.files||latest?.files)}`:'')+(subject||d?.subject||p.subject||kind==='template'?'':`<fieldset><legend>审批后需要签收的员工（可不选）</legend><div class="recipient-list">${s().employees.filter(e=>e.status!=='已离职').map(e=>`<label><input type="checkbox" name="recipients" value="${e.id}" ${(p.recipients||[]).includes(e.id)?'checked':''}>${esc(e.name)}</label>`).join('')}</div></fieldset>`),`data-kind="${esc(kind)}" data-subject="${esc(subject||d?.subject||p.subject||'')}" data-resubmit="${p.id||''}"`);}
function detail(label,x,body){const collection=['docRequests','purchases','sales','founderCandidates'].find(k=>s()[k]?.some(v=>v.id===x.id));if(collection){if(x.governance?.ended||x.governance?.withdrawn)body='<div class="notice">'+(x.governance.ended?'已终止':'已撤回')+'，历史保留，未计为完成。</div>'+body.replace(/<button[\s\S]*?<\/button>/g,'');if(!x.governance?.ended&&!['已通过','已入库','已完成','已立项'].includes(x.status))body+=button(x.governance?.withdrawn?'恢复待办理':'撤回 / 申请终止','workflowLifecycleForm',collection+'|'+x.id,['人事专员']);}ctx.panel(label,body+`<details class="founder-history"><summary>办理记录 · ${(x.history||[]).length} 条</summary>${hist(x)}</details>`,true);}
function founderPeoplePage(){const people=s().founders.filter(f=>(!peopleQuery||[f.name,f.job,f.project].join(' ').includes(peopleQuery))&&(!peopleOnlyPending||onboardingStatus(s(),f).some(t=>!t.done)));const todos=s().founders.flatMap(f=>onboardingStatus(s(),f).filter(t=>!t.done).map(t=>({...t,f})));return title('创业者人员','总经理立项后自动建档；办理账号、档案、协议和物资，全部完成后待办自动消除。')+`<div class="notice">人事待办 / 未完成事项 ${todos.length} 项 · ${s().founders.filter(f=>onboardingStatus(s(),f).every(t=>t.done)).length} 人手续齐备</div>`+`<div class="work-toolbar"><label>搜索创业者<input id="founder-people-query" placeholder="姓名、职务或项目" value="${esc(peopleQuery)}"></label><label>办理情况<select id="founder-people-filter"><option>全部</option><option ${peopleOnlyPending?'selected':''}>待办未完成</option></select></label>${button('查询','founderPeopleSearch')}${button('重置','founderPeopleReset')}</div>`+table(['名称','职务','项目','人事办理进度','操作'],people.map(f=>row(esc(f.name),esc(f.job),esc(f.project),onboardingStatus(s(),f).filter(t=>t.done).length+'/4 项完成',button('查看人员档案','founder',f.id))))+`<h2>待办与异常 ${todos.length}</h2>`+table(['创业者','事项','当前状态','操作'],todos.filter(t=>people.some(f=>f.id===t.f.id)).map(t=>row(esc(t.f.name),t.label,t.status,button('去办理','founderFlow',t.f.id+'|'+t.key))));}
function founderRecruitPage(){const state=s(),candidates=state.founderCandidates,needs=state.founderNeeds;const selected=candidates.filter(c=>(recruitStage==='全部'||(c.status==='已立项'?'已立项':recruiterStages[c.stage])===recruitStage)&&(!recruitQuery||[c.name,c.channel,c.project,c.job].join(' ').includes(recruitQuery)));return title('创业者招募','从用人需求到总经理立项，清楚跟进每一位候选人。',button('＋ 用人需求','founderNeedNew','',['创业发展总监'])+button('＋ 登记候选人','founderCandidateNew','',['人事专员']))+metrics([['招募需求',needs.length,'总监提出方向'],['跟进中',candidates.filter(c=>c.status==='跟进中').length,'人事持续跟进'],['待总经理立项',candidates.filter(c=>c.status==='跟进中'&&c.stage===5).length,'完成评估后审批'],['已立项',candidates.filter(c=>c.status==='已立项').length,'自动进入创业者人员']])+`<section class="work-library"><div class="agreement-tabs"><button data-op="recruitTab" data-id="candidates" aria-selected="${recruitTab==='candidates'}">候选人跟进 <span>${candidates.length}</span></button><button data-op="recruitTab" data-id="needs" aria-selected="${recruitTab==='needs'}">用人需求 <span>${needs.length}</span></button></div>${recruitTab==='needs'?`<div class="work-card-grid">${needs.map(n=>`<article class="work-record"><div>${chip(n.status)}<h3>${esc(n.title)}</h3></div><p>${esc(n.reason)}</p><div class="work-record-footer"><span>${candidates.filter(c=>c.needId===n.id).length} 位候选人</span>${button('查看需求','founderNeedDetail',n.id)}</div></article>`).join('')||emptyBlock('暂无用人需求','由创业者发展中心总监提出招募需求。')}</div>`:`<div class="work-toolbar"><label>搜索候选人<input id="recruit-query" placeholder="姓名、渠道、职务或项目" value="${esc(recruitQuery)}"></label><label>当前阶段<select id="recruit-stage">${['全部',...recruiterStages,'已立项'].map(x=>`<option ${x===recruitStage?'selected':''}>${x}</option>`).join('')}</select></label>${button('查询','recruitSearch')}${button('重置','recruitReset')}</div>${selected.length?table(['候选人 / 渠道','职务 / 项目','当前步骤','办理人','操作'],selected.map(c=>row('<b>'+esc(c.name)+'</b><small class="agreement-row-sub">'+esc(c.channel)+'</small>',esc(c.job||'事业主理人')+'<small class="agreement-row-sub">'+esc(c.project||needs.find(n=>n.id===c.needId)?.title||'')+'</small>',chip(c.status==='已立项'?'已立项':c.stage===5?'总经理立项审批':recruiterStages[c.stage]),c.status==='已立项'?'已完成':c.stage===5?'总经理':c.stage<2||c.stage===3?'人事专员':'创业发展总监',button('查看招募流程','founderCandidate',c.id)))):emptyBlock('暂无符合条件的候选人','登记候选人后可逐步记录面谈、评估及项目计划书。')}`}</section>`;}

function agreementsPage(){
 const docs=s().documents,templates=docs.filter(d=>d.kind==='template'),signed=docs.filter(d=>d.subject),requests=s().docRequests.filter(r=>r.subject||r.kind==='template'),pending=requests.filter(r=>r.status==='待审批');
 const tabs=[['templates','公司合同模板',templates.length],['signed','已签署合同',signed.length],['reviews','审批记录',requests.length]];
 const matches=d=>(agreementCategory==='全部'||d.category===agreementCategory)&&(!agreementQuery||[d.title,d.category,d.subject?names(d.subject):''].join(' ').toLowerCase().includes(agreementQuery.toLowerCase()));
 const current=(agreementTab==='templates'?templates:agreementTab==='signed'?signed:requests).filter(matches).filter(d=>agreementTab!=='reviews'||agreementStatus==='全部'||d.status===agreementStatus);
 const empty=`<div class="agreement-empty"><span>▤</span><h3>${agreementQuery||agreementCategory!=='全部'?'没有找到匹配的文件':'暂无'+tabs.find(t=>t[0]===agreementTab)[1]}</h3><p>${agreementTab==='templates'?'上传公司合同模板，审批通过后在这里统一使用。':agreementTab==='signed'?'从创业者人员档案上传签署文件，审批后自动归档。':'提交的文件新增与更新申请会显示在这里。'}</p></div>`;
 const cards=current.map(d=>{const latest=d.versions?.at(-1);if(!latest)return '';const updating=requests.some(r=>r.docId===d.id&&r.status==='待审批');return `<article class="agreement-card"><div class="agreement-card-top"><span class="agreement-file-icon">▤</span><span class="agreement-pill ${updating?'amber':''}">${updating?'新版待审批':d.subject?'已生效':'可使用'}</span></div><small class="agreement-category">${esc(d.category)}</small><h3>${esc(d.title)}</h3><p class="agreement-owner">${d.subject?'签约人 · '+esc(names(d.subject)):'公司标准模板'}</p><div class="agreement-meta"><span>版本 <b>V${d.versions.length}</b></span><span>生效日期 <b>${esc(latest.date||'—')}</b></span><span>附件 <b>${latest.files?.length||0} 份</b></span></div><div class="agreement-card-actions">${button('查看文件与版本','docVersion',d.id)}${!d.subject?button('更新模板','docEdit',d.id,['人事专员','创业发展总监']):''}</div></article>`;}).join('');
 return `<div class="agreements-workspace"><div class="agreement-heading"><div><span class="agreement-eyebrow">合同档案</span><h1>协议与合同</h1><p>统一维护公司模板，妥善留存每一份已签署合同。</p></div>${button('＋ 上传公司合同模板','agreementNew','',['人事专员','创业发展总监'])}</div><div class="agreement-stats"><div><small>可用模板</small><strong>${templates.length}<em>份</em></strong></div><div><small>已签署合同</small><strong>${signed.length}<em>份</em></strong></div><button data-op="agreementPending"><small>待审批</small><strong>${pending.length}<em>项</em></strong><span>查看待审批 →</span></button></div><section class="agreement-library"><div class="agreement-tabs" role="tablist" aria-label="合同分类">${tabs.map(([key,name,count])=>`<button role="tab" aria-selected="${agreementTab===key}" data-op="agreementTab" data-id="${key}">${name}<span>${count}</span></button>`).join('')}</div><div class="agreement-toolbar"><label class="agreement-search"><span>搜索文件</span><input id="agreement-search" placeholder="搜索文件名称、协议类型或签约人" value="${esc(agreementQuery)}"></label><label>协议类型<select id="agreement-category">${['全部','经营合作协议','创界平台服务协议'].map(t=>`<option ${t===agreementCategory?'selected':''}>${t}</option>`).join('')}</select></label>${agreementTab==='reviews'?`<label>审批状态<select id="agreement-status">${['全部','待审批','已驳回','已通过','已重提'].map(t=>`<option ${t===agreementStatus?'selected':''}>${t}</option>`).join('')}</select></label>`:''}${button('查询','agreementSearch')}${button('重置','agreementReset')}</div><div class="agreement-section-note"><p>${agreementTab==='templates'?'公司模板 · 新增及更新经过审批后生效':agreementTab==='signed'?'已签署合同 · 由创业者人员档案自动归档':'审批记录 · 查看申请文件、处理状态与审批意见'}</p><span>共 ${current.length} 份</span></div>${!current.length?empty:agreementTab==='reviews'?table(['申请文件','归属','申请日期','状态','操作'],current.map(x=>row('<b>'+esc(x.title)+'</b><small class="agreement-row-sub">'+esc(x.category)+'</small>',x.subject?esc(names(x.subject)):'公司合同模板',esc(x.created),'<span class="agreement-pill '+(x.status==='待审批'?'amber':x.status==='已驳回'?'red':'')+'">'+esc(x.status)+'</span>',button(x.status==='待审批'?'查看 / 审批':'查看记录','docRequest',x.id)))):'<div class="agreement-grid">'+cards+'</div>'}</section><p class="agreement-footer">模板更新保留历史版本；待审批的新版本不会替换当前有效文件。</p></div>`;
}
const flowNames={account:'OA账号与权限',profile:'创业者档案维护',contracts:'协议签署与归档',assets:'行政物资派发'};
function flowInfo(f,key,asset){
 const status=key==='account'?f.account?.status:key==='profile'?f.profile?.status:asset?.status;
 const specs={account:[['提交账号与权限','人事专员'],['审核必要权限','创业发展总监'],['确认账号开通','人事专员'],['完成','—']],profile:[['维护档案资料','人事专员'],['审核档案','创业发展总监'],['完成','—']],assets:[['选择物资并申请','人事专员'],['审核并预留库存','创业发展总监'],['领取确认与出库','人事专员'],['完成','—']]};
 const steps=specs[key]||[['签署并上传协议','人事专员'],['审核签署文件','管理层'],['生效归档','—']];
 let current=0;if(key==='account')current={'待审核':1,'待开通':2,'已开通':3}[status]??0;if(key==='profile')current={'待审核':1,'已确认':2}[status]??0;if(key==='assets')current={'待审核':1,'待派发':2,'使用中':3,'已耗用':3,'已归还':3}[status]??0;
 return {steps,current,rejected:status==='已驳回'};
}
function flowStrip(steps,current,rejected=false){return `<ol class="founder-steps" aria-label="办理流程">${steps.map(([name,owner],i)=>`<li class="${i<current?'done':i===current?'current':'future'}" ${i===current?'aria-current="step"':''}><span class="step-number">${i<current?'✓':i+1}</span><div><b>${name}</b><small>${i<current?'已完成':i===current?(current===steps.length-1?'已完成':rejected?'已驳回 · 请补充后重提':'当前步骤'):'待进行'} · ${owner}</small></div></li>`).join('')}</ol>`;}
function flowHeader(f,key,asset){const {steps,current,rejected}=flowInfo(f,key,asset);return `<div class="founder-flow-title"><span>${esc(f.name)} · ${esc(f.project)}</span><h3>${flowNames[key]}</h3></div>${flowStrip(steps,current,rejected)}`;}
function founderDetail(id){const f=s().founders.find(f=>f.id===id),steps=onboardingStatus(s(),f);ctx.panel(f.name+' · 人员档案',`<section class="founder-summary"><div class="founder-avatar">${esc(f.name.slice(0,1))}</div><div><h2>${esc(f.name)}</h2><p>${esc(f.job)} · ${esc(f.project)}</p></div><span class="badge">手续 ${steps.filter(t=>t.done).length}/4 完成</span></section><div class="founder-facts"><div><small>联系方式</small><b>${esc(f.profile?.contact||'待维护')}</b></div><div><small>合作开始日期</small><b>${esc(f.profile?.start||'待维护')}</b></div><div><small>OA账号</small><b>${esc(f.account?.account||'待开通')}</b></div><div><small>合作关系</small><b>${esc(f.relation||'待补充')}</b></div></div><h3>人事办理事项</h3><p class="muted">选择一项查看流程、当前办理人和相关资料。</p><div class="founder-work-grid">${steps.map((t,i)=>`<section class="founder-work-card"><div><small>0${i+1}</small><span class="badge ${t.done?'green':'amber'}">${t.done?'已完成':esc(t.status)}</span></div><h3>${flowNames[t.key]}</h3><p>${{account:'账号、权限及可见数据范围',profile:'基本信息、履历与档案附件',contracts:'经营合作协议、平台服务协议',assets:'库存申请、派发及归还记录'}[t.key]}</p>${button(t.done?'查看详情':'查看流程 / 办理','founderFlow',id+'|'+t.key)}</section>`).join('')}</div>`);}
function founderFlow(id,key){const state=s(),f=state.founders.find(f=>f.id===id);if(!f)return;let body='';
 if(key==='account'){const x=f.account;body=flowHeader(f,key)+`<section class="founder-info"><h3>本次账号与权限</h3><dl><dt>OA账号</dt><dd>${esc(x?.account||'待申请')}</dd><dt>必要功能权限</dt><dd>${esc(x?.permissions||'待填写')}</dd><dt>数据范围</dt><dd>${esc(x?.scope||'待填写')}</dd></dl>${x?.review?'<p>审核意见：'+esc(x.review)+'</p>':''}</section><div class="founder-next"><b>下一步</b><p>${x?.status==='待审核'?'创业发展总监核验账号和权限范围':x?.status==='待开通'?'人事专员完成开通后确认':x?.status==='已开通'?'流程已完成；权限变化时可重新申请':'人事专员填写账号、必要权限和数据范围'}</p>${x?.status==='待审核'?button('审核账号权限','onboardAccountReviewForm',id,['创业发展总监']):x?.status==='待开通'?button('确认账号开通','onboardAccountActivateForm',id,['人事专员']):button(x?.status==='已开通'?'申请调整权限':'填写账号权限申请','onboardAccountForm',id,['人事专员'])}</div>`;}
 if(key==='profile'){const x=f.profile;body=flowHeader(f,key)+`<section class="founder-info"><h3>档案资料</h3><dl><dt>职务 / 项目</dt><dd>${esc(x?.job||f.job)} / ${esc(x?.project||f.project)}</dd><dt>联系方式</dt><dd>${esc(x?.contact||'待维护')}</dd><dt>合作开始日期</dt><dd>${esc(x?.start||'待维护')}</dd><dt>履历与说明</dt><dd>${esc(x?.background||'待维护')}</dd></dl>${files(x?.files)}<p>${x?.review?'审核意见：'+esc(x.review):''}</p></section><div class="founder-next"><b>${x?.status==='已确认'?'档案已确认':'当前办理人：'+(x?.status==='待审核'?'创业发展总监':'人事专员')}</b><p>维护资料后提交审核；修改记录保留。</p>${x?.status==='待审核'?button('审核创业者档案','onboardProfileReviewForm',id,['创业发展总监']):button('维护创业者档案','onboardProfileForm',id,['人事专员'])}</div>`;}
 if(key==='contracts'){body=`<p>${esc(f.name)} · 两份协议分别签署、审核并归档。</p>`+['经营合作协议','创界平台服务协议'].map(category=>{const d=state.documents.find(d=>d.subject===id&&d.category===category),requests=state.docRequests.filter(r=>r.subject===id&&r.category===category),pending=requests.find(r=>r.status==='待审批'),rejected=requests.find(r=>r.status==='已驳回'),current=pending?1:d?2:0;return `<section class="founder-info"><h3>${category}</h3>${flowStrip([['签署并上传','人事专员'],['签署文件审核','管理层'],['生效归档','—']],current,!d&&!pending&&!!rejected)}<p>${pending?'等待管理层审核签署文件':d?'已生效 V'+d.versions.length:'请完成双方签署并上传文件'}</p>${pending?button('查看签署文件 / 审批','docRequest',pending.id):!d&&rejected?button('查看驳回意见 / 重提','docRequest',rejected.id):button(d?'上传新版已签署协议':'上传已签署协议','signedSpecific',id+'|'+category,['人事专员'])}${d?button('查看生效版本','docVersion',d.id):''}</section>`;}).join('');}
 if(key==='assets'){const assets=state.founderAssets.filter(a=>a.founderId===id),active=assets.find(a=>['待审核','待派发'].includes(a.status))||assets.find(a=>a.materialId);body=flowHeader(f,key,active)+`<div class="founder-next"><p>从行政仓库选择物资，审批后预留，领取确认后出库。每张申请单可单独查看进度。</p>${button('申请派发行政物资','onboardStockForm',id,['人事专员'])}</div>`+table(['物资 / 编码','数量','当前步骤','操作'],assets.map(a=>row(esc(a.name)+' / '+esc(a.code),a.quantity||1,esc(a.status),a.materialId?button('查看此单流程','onboardStock',a.id):'历史手工记录')));}
 const prefix={account:'onboardAccount',profile:'onboardProfile',assets:'onboardStock'}[key];const history=prefix?hist({history:(f.history||[]).filter(h=>h.action?.startsWith(prefix))}):'';ctx.panel(flowNames[key]+' · '+f.name,body+(history?`<details class="founder-history"><summary>本事项办理记录</summary>${history}</details>`:''));
}
function formFlowContext(action,id){const f=s().founders.find(f=>f.id===id);if(f&&action.startsWith('onboardAccount'))return flowHeader(f,'account')+(['onboardAccountReview','onboardAccountActivate'].includes(action)?`<div class="founder-info"><p>账号：${esc(f.account?.account)}</p><p>权限：${esc(f.account?.permissions)}</p><p>数据范围：${esc(f.account?.scope)}</p></div>`:'');if(f&&action.startsWith('onboardProfile'))return flowHeader(f,'profile')+(action==='onboardProfileReview'?`<div class="founder-info"><p>${esc(f.profile?.job)} · ${esc(f.profile?.project)}</p><p>${esc(f.profile?.contact)} · ${esc(f.profile?.start)}</p><p>${esc(f.profile?.background)}</p>${files(f.profile?.files)}</div>`:'');if(f&&action==='onboardStockApply')return flowHeader(f,'assets');const a=s().founderAssets.find(a=>a.id===id);if(a&&action.startsWith('onboardStock')){const owner=s().founders.find(f=>f.id===a.founderId);return flowHeader(owner,'assets',a)+`<p>${esc(a.name)} · ${esc(a.code)} · 数量 ${a.quantity}</p>`;}return '';}
function open(action,id){const state=s();let x;
 switch(action){
 case 'founderFlow':{const [fid,key]=id.split('|');founderFlow(fid,key);return;}
 case 'signedSpecific':{const [fid,category]=id.split('|');docForm(state.documents.find(d=>d.subject===fid&&d.category===category),{category},fid,'signed');return;}
 case 'signedForm':form('上传双方已签署协议','chooseSigned',id,select('category','协议类型',['经营合作协议','创界平台服务协议']));return;
 case 'onboardAccountForm':x=state.founders.find(f=>f.id===id);form('申请OA账号与必要权限','onboardAccountSubmit',id,field('account','OA账号','text',x.account?.account||'')+area('permissions','必要功能权限',x.account?.permissions||'')+area('scope','数据范围（具体项目或店铺）',x.account?.scope||x.project||'')+note()+'<p>总监审核后由人事确认开通。本原型演示办理记录，不实际创建OA账号；不记录密码。</p>');return;
 case 'onboardAccountReviewForm':form('审核账号权限','onboardAccountReview',id,review());return;
 case 'onboardAccountActivateForm':form('确认OA账号已开通','onboardAccountActivate',id,note());return;
 case 'onboardProfileForm':x=state.founders.find(f=>f.id===id);form('维护创业者档案','onboardProfileSubmit',id,field('job','职务','text',x.profile?.job||x.job)+field('project','项目','text',x.profile?.project||x.project)+field('contact','联系方式','text',x.profile?.contact||'')+field('start','合作开始日期','date',x.profile?.start||day())+area('background','履历与档案说明',x.profile?.background||'')+note()+upload);return;
 case 'onboardProfileReviewForm':form('审核创业者档案','onboardProfileReview',id,review());return;
 case 'onboardStockForm':{const stock=ctx.inventory?.()?.materials?.filter(m=>m.status==='在库')||[];if(!stock.length){ctx.panel('行政物资派发','<p>行政仓库暂无在库物资。请先在人事行政管理 → 行政物资仓库完成采购入库。</p>');return;}form('从行政物资申请派发','onboardStockApply',id,select('materialId','行政仓库物资',stock.map(m=>[m.id,m.name+' / '+m.code+' / '+m.kind+' / 在库 '+m.quantity]))+field('quantity','派发数量','number',1,'min="1" step="1"')+note());return;}
 case 'onboardStock':x=state.founderAssets.find(a=>a.id===id);detail(x.name+' · '+x.status,x,`${flowHeader(state.founders.find(f=>f.id===x.founderId),'assets',x)}<p>${esc(x.code)} · ${x.kind} · 数量 ${x.quantity} · ${esc(x.note)}</p>${files(x.files)}${files(x.returnFiles)}${x.status==='待审核'?button('审核物资派发','onboardStockReviewForm',id,['创业发展总监']):x.status==='待派发'?button('确认出库与领取','onboardStockDeliverForm',id,['人事专员']):x.status==='使用中'?button('归还行政仓库','onboardStockReturnForm',id,['人事专员']):''}`);return;
 case 'onboardStockReviewForm':form('审核物资派发','onboardStockReview',id,review());return;
 case 'onboardStockDeliverForm':form('确认出库与领取','onboardStockDeliver',id,note()+upload);return;
 case 'onboardStockReturnForm':form('归还行政仓库','onboardStockReturn',id,note()+upload);return;
 case 'documentTab':documentTab=id;ctx.render();return;
 case 'documentSearch':documentQuery=document.querySelector('#document-query').value.trim();ctx.render();return;
 case 'documentReset':documentQuery='';ctx.render();return;
 case 'founderPeopleSearch':peopleQuery=document.querySelector('#founder-people-query').value.trim();peopleOnlyPending=document.querySelector('#founder-people-filter').value==='待办未完成';ctx.render();return;
 case 'founderPeopleReset':peopleQuery='';peopleOnlyPending=false;ctx.render();return;
 case 'warehouseTab':warehouseTab=id;warehouseQuery='';warehouseFilter='全部';ctx.render();return;
 case 'warehouseSearch':warehouseQuery=document.querySelector('#warehouse-query').value.trim();warehouseFilter=document.querySelector('#warehouse-filter').value;ctx.render();return;
 case 'warehouseReset':warehouseQuery='';warehouseFilter='全部';ctx.render();return;
 case 'recruitTab':recruitTab=id;ctx.render();return;
 case 'recruitSearch':recruitQuery=document.querySelector('#recruit-query').value.trim();recruitStage=document.querySelector('#recruit-stage').value;ctx.render();return;
 case 'recruitReset':recruitQuery='';recruitStage='全部';ctx.render();return;
 case 'founderNeedDetail':x=state.founderNeeds.find(n=>n.id===id);detail('招募需求 · '+x.title,x,`<div class="work-context"><h3>${esc(x.title)}</h3><p>${chip(x.status)}</p><p>用人理由：${esc(x.reason)}</p></div><h3>关联候选人</h3>${table(['姓名','渠道','操作'],state.founderCandidates.filter(c=>c.needId===id).map(c=>row(esc(c.name),esc(c.channel),button('查看招募流程','founderCandidate',c.id))))}`);return;
 case 'agreementTab':agreementTab=id;agreementStatus='全部';ctx.render();return;
 case 'agreementPending':agreementTab='reviews';agreementStatus='待审批';agreementQuery='';agreementCategory='全部';ctx.render();return;
 case 'agreementSearch':agreementQuery=document.querySelector('#agreement-search').value.trim();agreementCategory=document.querySelector('#agreement-category').value;agreementStatus=document.querySelector('#agreement-status')?.value||'全部';ctx.render();return;
 case 'agreementReset':agreementQuery='';agreementCategory='全部';agreementStatus='全部';ctx.render();return;
 case 'docFilter':docFilter=id;ctx.render();return;
 case 'warehouse':ctx.navigate('行政物资仓库');return;
 case 'sales':ctx.navigate('物资销售');return;
 case 'agreements':ctx.navigate('协议档案');return;
 case 'workflowLifecycleForm':{const [collection,recordId]=id.split('|'),item=state[collection].find(x=>x.id===recordId);form('撤回或申请终止','workflowLifecycle',recordId,'<input type="hidden" name="collection" value="'+collection+'"><input type="hidden" name="decision" value="'+(item.governance?.withdrawn?'恢复':'申请')+'">'+note()+'<p>未启动可撤回；已启动须负责人确认终止。已完成事项不能取消。</p>');return;}
 case 'docNew':docForm();return;
 case 'agreementNew':docForm(null,null,null,'template');return;
 case 'docEdit':docForm(state.documents.find(d=>d.id===id));return;
 case 'docResubmit':x=state.docRequests.find(x=>x.id===id);docForm(state.documents.find(d=>d.id===x.docId),x,x.subject);return;
 case 'docVersion':x=state.documents.find(x=>x.id===id);ctx.panel(x.title,x.versions.slice().reverse().map(v=>`<article class="version"><h3>V${v.version} · ${v.date}</h3><p>${v.approvedBy?'审批：'+esc(v.approvedBy)+' / '+esc(v.approvalNote):'原有演示版本'}</p><pre>${esc(v.content)}</pre>${files(v.files)}</article>`).join(''),true);return;
 case 'docRequest':x=state.docRequests.find(x=>x.id===id);detail(x.title+' · '+x.status,x,`${flowStrip([[x.subject?'签署并上传':'上传或更新文件','人事专员'],['管理层审核','管理层'],['生效归档','系统']],x.status==='已通过'?2:x.status==='待审批'?1:0,x.status==='已驳回')}<p>申请：${esc(x.applicant)} · ${esc(x.category)}</p><p>原因：${esc(x.reason)}</p><pre>${esc(x.content)}</pre>${files(x.files)}<p>签收对象：${x.recipients.map(names).map(esc).join('、')||'无需签收'}</p>${x.status==='待审批'?button(docReviewer(x)+'审批','docReviewForm',id,[docReviewer(x)]):x.status==='已驳回'?button('修改重提','docResubmit',id,[x.applicant]):''}`);return;
 case 'docReviewForm':x=state.docRequests.find(x=>x.id===id);form('管理层审批文件','docReview',id,`<div class="work-context"><h3>${esc(x.title)}</h3><p>${esc(x.category)} · 申请人 ${esc(x.applicant)}</p><p>${esc(x.reason)}</p>${files(x.files)}</div>`+review());return;
 case 'purchaseNew':x=state.purchases.find(p=>p.id===id);form('采购物资申请','purchaseSubmit',x?.id,field('name','物资名称','text',x?.name||'')+select('kind','物资类型',['有价资产','易耗品'],x?.kind)+field('quantity','数量','number',x?.quantity||1,'min="1" step="1"')+field('value','单件价值（元）','number',x?.value||'','min="0.01" step="0.01"')+field('years','折价年限（易耗品可填0）','number',x?.years??'','min="0" step="0.1"')+area('reason','采购理由',x?.reason||''));return;
 case 'purchase':x=state.purchases.find(x=>x.id===id);detail(x.name+' · '+x.status,x,`${purchaseSummary(x)}<h3>到货凭证</h3>${files(x.files)||'<p class="muted">到货后由人事上传采购及验收凭证。</p>'}<div class="work-next"><p>${x.status==='已入库'?'采购流程已完成，物资已进入库存台账。':'根据上方当前环节完成办理，提交后自动更新流程进度。'}</p></div>${x.status==='财务审核'?button('财务审核','purchaseReviewForm',id,['财务负责人']):x.status==='采购入库'?button('登记采购到货','purchaseReceiveForm',id,['人事专员']):x.status==='上级确认'?button('确认入库','purchaseConfirmForm',id,['创业发展总监']):x.status==='已驳回'?button('修改采购申请','purchaseNew',id,['人事专员']):''}`);return;
 case 'purchaseReviewForm':form('财务审核采购','purchaseReview',id,review());return;
 case 'purchaseReceiveForm':form('登记到货及采购凭证','purchaseReceive',id,note()+upload);return;
 case 'purchaseConfirmForm':form('上级确认入库','purchaseConfirm',id,review());return;
 case 'material':x=state.materials.find(x=>x.id===id);detail(x.name+' · '+x.code,x,`<section class="work-context"><h3>${esc(x.name)}</h3><p>${esc(x.code)} · ${chip(x.status)}</p><div class="work-facts"><span>物资类型<b>${x.kind}</b></span><span>原值<b>${money(x.value)}</b></span><span>估算剩余价值<b>${money(remaining(x))}</b></span><span>折价年限<b>${x.years} 年</b></span></div><p>库存数量：${x.quantity} · 领用人：${esc(names(x.holder))}</p></section><h3>可办理事项</h3><p class="muted">${x.status==='在库'?'选择派发给员工，或记录损坏情况。':x.status==='领用中'?'使用中的资产可归还或换发；记录保留在库存台账。':'当前物资状态下暂不支持派发。'}</p>${x.status==='在库'?button('派发','issueForm',id,['人事专员'])+button('标记损坏','damageForm',id,['人事专员']):x.status==='领用中'&&x.holder?.startsWith('founder:')?'<p>此资产由创业者领用，请从创业者人员档案办理归还或更换。</p>':x.status==='领用中'?button('归还','returnForm',id,['人事专员'])+button('换发资产','replaceForm',id,['人事专员']):''}`);return;
 case 'issueForm':form('派发物资','issue',id,select('holder','领取人员',recipients(state).filter(e=>e.kind==='员工').map(e=>[e.id,e.name+' · '+e.kind]))+field('quantity','派发数量','number',1,'min="1" step="1"')+note());return;
 case 'returnForm':form('归还资产','return',id,select('damaged','是否损坏',['否','是'])+note());return;
 case 'replaceForm':form('换发资产（原件同时归还）','replace',id,select('replacement','替换资产',state.materials.filter(m=>m.status==='在库'&&m.kind==='有价资产').map(m=>[m.id,m.name+' / '+m.code]))+select('damaged','归还原件是否损坏',['否','是'])+note());return;
 case 'damageForm':form('标记损坏','damage',id,note());return;
 case 'saleNew':form('物资销售申请','saleSubmit','',select('materialId','待销售物资',state.materials.filter(m=>['在库','损坏待处理'].includes(m.status)).map(m=>[m.id,m.name+' / '+m.code+' / 估算剩余 ¥'+remaining(m)]))+field('quantity','数量','number',1,'min="1" step="1"')+field('remaining','申报剩余价值（合计元）','number','','min="0" step="0.01"')+area('reason','销售原因'));return;
 case 'sale':x=state.sales.find(x=>x.id===id);detail(x.name+' · '+x.status,x,`${saleSummary(x)}<p>申报剩余 ¥${x.remaining} · 数量 ${x.quantity} · 实际售价 ${x.price??'未销售'} · ${x.accounting||'待财务确认入账要求'}</p>${files(x.files)}${x.status==='财务审核'?button('财务审核','saleReviewForm',id,['财务负责人']):x.status==='待销售'?button('登记销售结果','saleExecuteForm',id,['人事专员']):x.status==='财务结案'?button('财务入账 / 结案','saleCloseForm',id,['财务负责人']):x.status==='已驳回'?button('修改销售申请','saleResubmitForm',id,['人事专员']):''}`);return;
 case 'saleResubmitForm':x=state.sales.find(x=>x.id===id);form('修改销售申请','saleResubmit',id,field('remaining','申报剩余价值（元）','number',x.remaining,'min="0" step="0.01"')+area('note','整改说明与销售理由',x.reason));return;
 case 'saleReviewForm':form('财务审核销售','saleReview',id,review()+select('accounting','入账要求',['需入账','无需入账']));return;
 case 'saleExecuteForm':form('登记实际销售结果','saleExecute',id,field('price','实际销售金额（元）','number','','min="0" step="0.01"')+note()+upload);return;
 case 'saleCloseForm':x=state.sales.find(x=>x.id===id);form('财务入账 / 结案','saleClose',id,`<p>${esc(x.accounting)}</p>`+(x.accounting==='需入账'?field('voucher','入账凭证号'):'')+note());return;
 case 'founderNeedNew':form('总监提出招募需求','founderNeed','',field('title','用人需求')+area('reason','需求理由'));return;
 case 'founderCandidateNew':form('录入创业候选人','founderCandidate','',select('needId','关联需求',state.founderNeeds.map(n=>[n.id,n.title]))+field('name','姓名')+field('channel','招聘渠道')+field('job','职务','text','事业主理人')+field('project','拟负责项目')+select('relation','关系',['投资合作','雇佣']));return;
 case 'employeeFounderNew':form('全职员工登记为事业主理人','employeeFounder','',select('employeeId','员工',state.employees.filter(e=>e.status!=='已离职').map(e=>[e.id,e.name])));return;
 case 'founderCandidate':x=state.founderCandidates.find(x=>x.id===id);detail(x.name+' · '+(x.status==='已立项'?'已立项':recruiterStages[x.stage]),x,`<div class="work-context"><h3>${esc(x.name)}</h3><p>${esc(x.channel)} · ${x.relation} · ${esc(x.project||'')}</p></div>${recruitSteps(x)}<h3>项目计划书</h3>${x.planFiles?.length?files(x.planFiles):'<p class="muted">到项目计划书阶段由人事上传。</p>'}<div class="work-next">${x.status==='跟进中'?'<p>当前步骤：'+esc(recruiterStages[x.stage])+' · '+(x.stage===5?'总经理':x.stage<2||x.stage===3?'人事专员':'创业发展总监')+'</p>':'<p>立项完成，已自动建立创业者档案。</p>'}</div>${x.status==='跟进中'?button('处理当前步骤','founderAdvanceForm',id,x.stage===5?['总经理']:x.stage<2||x.stage===3?['人事专员']:['创业发展总监']):''}`);return;
 case 'founderAdvanceForm':x=state.founderCandidates.find(x=>x.id===id);form(recruiterStages[x.stage]+' · '+x.name,'founderAdvance',id,select('result','处理结果',x.stage?['通过','驳回']:['通过'])+note()+(x.stage===3?upload+'<p>创业者线下提交计划书，由人事上传。</p>':''));return;
 case 'founder':founderDetail(id);return;
 case 'founderProfileForm':x=state.founders.find(f=>f.id===id);form('维护创业者档案','founderProfile',id,field('job','职务','text',x.job)+field('project','项目','text',x.project));return;
 case 'founderAssetForm':form('创业者办公资产申请','founderAssetApply',id,field('name','资产名称')+field('code','资产编码')+field('value','资产价值（元）','number','','min="0" step="0.01"')+note());return;
 case 'founderAsset':x=state.founderAssets.find(a=>a.id===id);detail(x.name+' · '+x.status,x,'<p>创业者：'+esc(names(x.founderId))+' · '+esc(x.code)+' · ¥'+x.value+'</p><p>'+esc(x.note)+'</p>'+files(x.files)+files(x.returnFiles)+(x.status==='待审核'?button('审核派发申请','founderAssetReviewForm',id,['创业发展总监']):x.status==='待派发'?button('确认派发','founderAssetDeliverForm',id,['人事专员']):x.status==='使用中'?button('登记归还','founderAssetReturnForm',id,['人事专员']):''));return;
 case 'founderAssetReviewForm':form('审核办公资产派发','founderAssetReview',id,review());return;
 case 'founderAssetDeliverForm':form('派发与领取凭证','founderAssetDeliver',id,note()+upload);return;
 case 'founderAssetReturnForm':form('归还资产及凭证','founderAssetReturn',id,note()+upload);return;
 case 'founderAgreement':docForm(state.documents.find(d=>d.subject===id&&d.category==='经营合作协议'),null,id);return;
 case 'founderSetupForm':form('人事手续与物资核验','founderSetup',id,area('note','记录签署核验、账号安排及物资派发情况（无需派发也需说明）')+upload);return;
 case 'founderSetupReviewForm':form('总监审核人事手续','founderSetupReview',id,review());return;
 case 'ventureNew':x=state.ventures.find(p=>p.id===id);form('建立项目 · 提交总经理审核','ventureSubmit',x?.id,field('title','项目名称','text',x?.title||'')+select('founderId','项目负责人',state.founders.map(f=>[f.id,f.name+' · '+f.relation+(ready(state,f)?'':' · 手续待完善')]),x?.founderId)+field('shop','项目店铺（与营业执照至少填一项）','text',x?.shop||'','data-optional')+field('license','营业执照主体 / 编号（有则填写）','text','','data-optional')+[0,1,2].map(i=>`<fieldset><legend>第${i+1}阶段</legend>${field('budget'+i,'阶段预算（元）','number',x?.phases[i].budget||'','min="0.01" step="0.01"')}${area('goal'+i,'阶段目标',x?.phases[i].goal||'')}${field('due'+i,'截止日期','date',x?.phases[i].due||'','min="'+day()+'"')}</fieldset>`).join(''));document.querySelectorAll('[data-optional]').forEach(e=>e.required=false);return;
 case 'venture':x=state.ventures.find(x=>x.id===id);detail(x.title+' · '+x.status,x,`<p>负责人 ${esc(names(x.founderId))} · ${esc(x.shop||'')} · ${esc(x.license||'')}</p>${x.phases.map((p,i)=>`<div class="version"><h3>第${i+1}阶段 · ¥${p.budget} · ${i<=x.releasedPhase?'已批准':'待批准'}</h3><p>${esc(p.goal)} · 截止 ${p.due}</p></div>`).join('')}${x.status==='总经理审核'?button('总经理审核','ventureReviewForm',id,['总经理']):x.status==='已驳回'?button('修改并重新提交','ventureNew',id,['创业发展总监']):button('更新月度评估','ventureMonthForm',id,['创业发展总监'])+button('申请下一阶段预算','fundingSubmitForm',id,['创业发展总监'])}<h3>月度预算与评估</h3><p>累计预算使用：¥${x.months.reduce((n,m)=>n+m.used,0)} / 已批准预算：¥${x.phases.slice(0,x.releasedPhase+1).reduce((n,p)=>n+p.budget,0)}</p>${x.months.map(m=>`<div class="version"><b>${m.month} · 第${m.phase+1}阶段</b><p>使用 ¥${m.used} · 达成 ${m.rate}% · ${esc(m.note)}</p>${files(m.files)}</div>`).join('')}${x.monthHistory?.length?'<h3>月度评估历史修订</h3>'+x.monthHistory.map(m=>'<p>'+m.month+' · 第'+(m.phase+1)+'阶段 · ¥'+m.used+' · '+m.rate+'% · '+esc(m.note)+'</p>'+files(m.files)).join(''):''}<h3>阶段资金审批</h3>${x.funding.map(f=>`<div class="version"><p>第${f.phase+1}阶段 ¥${x.phases[f.phase].budget} · ${f.status}</p><p>${esc(f.note)} ${esc(f.review||'')}</p>${f.status==='待审核'?button('审批阶段预算','fundingReviewForm',x.id+':'+f.id,['总经理']):''}</div>`).join('')}`);return;
 case 'ventureReviewForm':form('总经理审核项目','ventureReview',id,review());return;
 case 'ventureMonthForm':x=state.ventures.find(x=>x.id===id);form('月度项目评估','ventureMonth',id,field('month','月份','month',day().slice(0,7))+select('phase','阶段',x.phases.slice(0,x.releasedPhase+1).map((p,i)=>[i,'第'+(i+1)+'阶段']))+field('used','本月预算使用金额（元）','number','','min="0" step="0.01"')+field('rate','阶段目标达成率（%）','number','','min="0" max="100"')+area('note','对项目的评估')+upload);return;
 case 'fundingSubmitForm':form('申请下一阶段预算','fundingSubmit',id,note());return;
 case 'fundingReviewForm':{const [pid,fid]=id.split(':');form('总经理审批阶段预算','fundingReview',pid,review(),`data-funding-id="${fid}"`);return;}
 }
}
export function initOperations(context){ctx=context;
 document.addEventListener('input',e=>{const f=e.target.closest('[data-op-form="purchaseSubmit"]');if(!f)return;const total=f.querySelector('#purchase-total'),quantity=Number(f.elements.quantity.value),value=Number(f.elements.value.value);if(total)total.textContent=quantity>0&&value>0?money(quantity*value):'待填写数量与单价';});
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-op]');if(!b)return;try{if(b.dataset.op==='download')await download(b.dataset.id);else open(b.dataset.op,b.dataset.id);}catch(error){ctx.toast(error.message);}});
 document.addEventListener('submit',async e=>{const f=e.target.closest('[data-op-form]');if(!f)return;e.preventDefault();const action=f.dataset.opForm,fd=new FormData(f),v=Object.fromEntries(fd);const submit=f.querySelector('[type="submit"]');submit.disabled=true;try{
   if(action==='chooseSigned'){const d=s().documents.find(d=>d.subject===f.dataset.id&&d.category===v.category);docForm(d,{category:v.category},f.dataset.id,'signed');return;}
   if(action==='chooseAgreement'){docForm(null,null,v.subject);return;}
   const actor=r();v.actorIdentity={person:new URLSearchParams(location.search).get('person')||actor,personId:new URLSearchParams(location.search).get('personId')||'',center:3};v.id=f.dataset.id;v.files=await storeFiles(fd.getAll('files').filter(x=>x instanceof File));
   if(action==='docSubmit'){v.kind=f.dataset.kind;v.docId=v.id||null;v.subject=f.dataset.subject;v.resubmit=f.dataset.resubmit;v.recipients=fd.getAll('recipients');if(!v.files.length)v.files=v.resubmit?s().docRequests.find(x=>x.id===v.resubmit)?.files||[]:s().documents.find(x=>x.id===v.docId)?.versions.at(-1).files||[];}
   if(action==='founderAssetApply')v.founderId=v.id;
   if(action==='ventureSubmit')v.phases=[0,1,2].map(i=>({budget:v['budget'+i],goal:v['goal'+i],due:v['due'+i]}));
   if(action==='fundingReview')v.fundingId=f.dataset.fundingId;
   if(actor!==r())throw Error('角色已变更，请重新提交');
   if(ctx.runCommand){await ctx.runCommand(action,v,actor);}else{const draft=structuredClone(s());command(draft,action,v,actor);ctx.commit(draft);}ctx.close();ctx.render();if(action.startsWith('onboard')){const key=action.startsWith('onboardAccount')?'account':action.startsWith('onboardProfile')?'profile':'assets';const owner=action.startsWith('onboardStock')&&action!=='onboardStockApply'?s().founderAssets.find(a=>a.id===v.id)?.founderId:v.id;if(owner)founderFlow(owner,key);}else if(action==='founderAdvance'){open('founderCandidate',v.id);}else if(['purchaseReview','purchaseReceive','purchaseConfirm'].includes(action)){open('purchase',v.id);}else if(['saleReview','saleExecute','saleClose'].includes(action)){open('sale',v.id);}ctx.toast('已保存，流程状态已更新');
 }catch(error){f.querySelector('.form-error').textContent=error.message;}finally{submit.disabled=false;}});
}
export function operationsPage(page){return page==='行政物资仓库'?warehousePage():page==='物资销售'?salesPage():page==='创业者人员'?founderPeoplePage():page==='招募'?founderRecruitPage():page==='创业者管理'?foundersPage():page==='项目管理'?venturesPage():documentsPage(['协议档案','协议与合同'].includes(page)?'agreements':'');}
